package com.bet.orms;
// Generated 2018-4-22 12:09:43 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * AdminPayLogInfo generated by hbm2java
 */
@Entity
@Table(name = "admin_pay_log_info")
@Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
public class AdminPayLogInfo implements java.io.Serializable
{
	private static final long serialVersionUID = -6347118692156308882L;
	private Integer id;
	private String adminId;
	private String payType;
	private String payId;
	private long money;
	private byte moneyUnit;
	private long addDateLong;

	public AdminPayLogInfo()
	{
	}

	public AdminPayLogInfo(String adminId, String payType, String payId, long money, byte moneyUnit, long addDateLong)
	{
		this.adminId = adminId;
		this.payType = payType;
		this.payId = payId;
		this.money = money;
		this.moneyUnit = moneyUnit;
		this.addDateLong = addDateLong;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "admin_id", nullable = false, length = 16)
	public String getAdminId()
	{
		return this.adminId;
	}

	public void setAdminId(String adminId)
	{
		this.adminId = adminId;
	}

	@Column(name = "pay_type", nullable = false, length = 16)
	public String getPayType()
	{
		return this.payType;
	}

	public void setPayType(String payType)
	{
		this.payType = payType;
	}

	@Column(name = "pay_id", nullable = false, length = 16)
	public String getPayId()
	{
		return this.payId;
	}

	public void setPayId(String payId)
	{
		this.payId = payId;
	}

	@Column(name = "money", nullable = false)
	public long getMoney()
	{
		return this.money;
	}

	public void setMoney(long money)
	{
		this.money = money;
	}

	@Column(name = "money_unit", nullable = false)
	public byte getMoneyUnit()
	{
		return this.moneyUnit;
	}

	public void setMoneyUnit(byte moneyUnit)
	{
		this.moneyUnit = moneyUnit;
	}

	@Column(name = "add_date_long", nullable = false)
	public long getAddDateLong()
	{
		return this.addDateLong;
	}

	public void setAddDateLong(long addDateLong)
	{
		this.addDateLong = addDateLong;
	}
}
