package com.bet.orms;
// Generated 2018-3-29 21:47:22 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * AdminInfo generated by hbm2java
 */
@Entity
@Table(name = "admin_info", uniqueConstraints = @UniqueConstraint(columnNames = "user_id"))
@Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
public class AdminInfo implements java.io.Serializable
{
	private static final long serialVersionUID = 9180233407448868082L;
	private Integer id;
	private String userId;
	private String password;
	private byte userLevel;
	private String name;
	private String picUrl;
	private byte status;
	private long addDateLong;
	private long updateDateLong;

	public AdminInfo()
	{
	}

	public AdminInfo(String userId, String password, byte userLevel, byte status, long addDateLong, long updateDateLong)
	{
		this.userId = userId;
		this.password = password;
		this.userLevel = userLevel;
		this.status = status;
		this.addDateLong = addDateLong;
		this.updateDateLong = updateDateLong;
	}

	public AdminInfo(String userId, String password, byte userLevel, String name, String picUrl, byte status, long addDateLong, long updateDateLong)
	{
		this.userId = userId;
		this.password = password;
		this.userLevel = userLevel;
		this.name = name;
		this.picUrl = picUrl;
		this.status = status;
		this.addDateLong = addDateLong;
		this.updateDateLong = updateDateLong;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "user_id", unique = true, nullable = false, length = 16)
	public String getUserId()
	{
		return this.userId;
	}

	public void setUserId(String userId)
	{
		this.userId = userId;
	}

	@Column(name = "password", nullable = false, length = 32)
	public String getPassword()
	{
		return this.password;
	}

	public void setPassword(String password)
	{
		this.password = password;
	}

	@Column(name = "user_level", nullable = false)
	public byte getUserLevel()
	{
		return this.userLevel;
	}

	public void setUserLevel(byte userLevel)
	{
		this.userLevel = userLevel;
	}

	@Column(name = "name", length = 16)
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	@Column(name = "pic_url", length = 256)
	public String getPicUrl()
	{
		return this.picUrl;
	}

	public void setPicUrl(String picUrl)
	{
		this.picUrl = picUrl;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus()
	{
		return this.status;
	}

	public void setStatus(byte status)
	{
		this.status = status;
	}

	@Column(name = "add_date_long", nullable = false)
	public long getAddDateLong()
	{
		return this.addDateLong;
	}

	public void setAddDateLong(long addDateLong)
	{
		this.addDateLong = addDateLong;
	}

	@Column(name = "update_date_long", nullable = false)
	public long getUpdateDateLong()
	{
		return this.updateDateLong;
	}

	public void setUpdateDateLong(long updateDateLong)
	{
		this.updateDateLong = updateDateLong;
	}
}
