package com.bet.orms;
// Generated 2018-3-29 21:47:22 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * AdviceTypeInfo generated by hbm2java
 */
@Entity
@Table(name = "advice_type_info", uniqueConstraints = @UniqueConstraint(columnNames = "type_id"))
@Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
public class AdviceTypeInfo implements java.io.Serializable
{
	private static final long serialVersionUID = 3628715118158719378L;
	private Integer id;
	private String typeId;
	private String name;
	private byte status;
	private long addDateLong;
	private long updateDateLong;

	public AdviceTypeInfo()
	{
	}

	public AdviceTypeInfo(String typeId, String name, byte status, long addDateLong, long updateDateLong)
	{
		this.typeId = typeId;
		this.name = name;
		this.status = status;
		this.addDateLong = addDateLong;
		this.updateDateLong = updateDateLong;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "type_id", unique = true, nullable = false, length = 16)
	public String getTypeId()
	{
		return this.typeId;
	}

	public void setTypeId(String typeId)
	{
		this.typeId = typeId;
	}

	@Column(name = "name", nullable = false, length = 32)
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus()
	{
		return this.status;
	}

	public void setStatus(byte status)
	{
		this.status = status;
	}

	@Column(name = "add_date_long", nullable = false)
	public long getAddDateLong()
	{
		return this.addDateLong;
	}

	public void setAddDateLong(long addDateLong)
	{
		this.addDateLong = addDateLong;
	}

	@Column(name = "update_date_long", nullable = false)
	public long getUpdateDateLong()
	{
		return this.updateDateLong;
	}

	public void setUpdateDateLong(long updateDateLong)
	{
		this.updateDateLong = updateDateLong;
	}
}
