package com.bet.orms;
// Generated 2018-3-29 21:47:22 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * AdviceReplyInfo generated by hbm2java
 */
@Entity
@Table(name = "advice_reply_info", uniqueConstraints = @UniqueConstraint(columnNames = "reply_id"))
@Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
public class AdviceReplyInfo implements java.io.Serializable
{
	private static final long serialVersionUID = 38736696384279593L;
	private Integer id;
	private String replyId;
	private String adviceId;
	private String content;
	private String parentId;
	private byte status;
	private long addDateLong;

	public AdviceReplyInfo()
	{
	}

	public AdviceReplyInfo(String replyId, String adviceId, String content, byte status, long addDateLong)
	{
		this.replyId = replyId;
		this.adviceId = adviceId;
		this.content = content;
		this.status = status;
		this.addDateLong = addDateLong;
	}

	public AdviceReplyInfo(String replyId, String adviceId, String content, String parentId, byte status, long addDateLong)
	{
		this.replyId = replyId;
		this.adviceId = adviceId;
		this.content = content;
		this.parentId = parentId;
		this.status = status;
		this.addDateLong = addDateLong;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "reply_id", unique = true, nullable = false, length = 16)
	public String getReplyId()
	{
		return this.replyId;
	}

	public void setReplyId(String replyId)
	{
		this.replyId = replyId;
	}

	@Column(name = "advice_id", nullable = false, length = 16)
	public String getAdviceId()
	{
		return this.adviceId;
	}

	public void setAdviceId(String adviceId)
	{
		this.adviceId = adviceId;
	}

	@Column(name = "content", nullable = false, length = 128)
	public String getContent()
	{
		return this.content;
	}

	public void setContent(String content)
	{
		this.content = content;
	}

	@Column(name = "parent_id", length = 16)
	public String getParentId()
	{
		return this.parentId;
	}

	public void setParentId(String parentId)
	{
		this.parentId = parentId;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus()
	{
		return this.status;
	}

	public void setStatus(byte status)
	{
		this.status = status;
	}

	@Column(name = "add_date_long", nullable = false)
	public long getAddDateLong()
	{
		return this.addDateLong;
	}

	public void setAddDateLong(long addDateLong)
	{
		this.addDateLong = addDateLong;
	}
}
