package com.bet.orms;
// Generated 2018-3-29 21:47:22 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * ApiRequestLogInfo generated by hbm2java
 */
@Entity
@Table(name = "api_request_log_info")
@Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
public class ApiRequestLogInfo implements java.io.Serializable
{
	private static final long serialVersionUID = 8748952668477539818L;
	private Integer id;
	private String userId;
	private String ip;
	private String url;
	private String agentId;
	private String platform;
	private String deviceName;
	private String sysVersion;
	private String versionCode;
	private String sign;
	private String v;
	private String sessionId;
	private String params;
	private long addDateLong;

	public ApiRequestLogInfo()
	{
	}

	public ApiRequestLogInfo(long addDateLong)
	{
		this.addDateLong = addDateLong;
	}

	public ApiRequestLogInfo(String userId, String ip, String url, String agentId, String platform, String deviceName, String sysVersion, String versionCode, String sign, String v, String sessionId,
		String params, long addDateLong)
	{
		this.userId = userId;
		this.ip = ip;
		this.url = url;
		this.agentId = agentId;
		this.platform = platform;
		this.deviceName = deviceName;
		this.sysVersion = sysVersion;
		this.versionCode = versionCode;
		this.sign = sign;
		this.v = v;
		this.sessionId = sessionId;
		this.params = params;
		this.addDateLong = addDateLong;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "user_id", length = 32)
	public String getUserId()
	{
		return this.userId;
	}

	public void setUserId(String userId)
	{
		this.userId = userId;
	}

	@Column(name = "ip", length = 16)
	public String getIp()
	{
		return this.ip;
	}

	public void setIp(String ip)
	{
		this.ip = ip;
	}

	@Column(name = "url", length = 256)
	public String getUrl()
	{
		return this.url;
	}

	public void setUrl(String url)
	{
		this.url = url;
	}

	@Column(name = "agent_id", length = 16)
	public String getAgentId()
	{
		return this.agentId;
	}

	public void setAgentId(String agentId)
	{
		this.agentId = agentId;
	}

	@Column(name = "platform", length = 16)
	public String getPlatform()
	{
		return this.platform;
	}

	public void setPlatform(String platform)
	{
		this.platform = platform;
	}

	@Column(name = "device_name", length = 32)
	public String getDeviceName()
	{
		return this.deviceName;
	}

	public void setDeviceName(String deviceName)
	{
		this.deviceName = deviceName;
	}

	@Column(name = "sys_version", length = 32)
	public String getSysVersion()
	{
		return this.sysVersion;
	}

	public void setSysVersion(String sysVersion)
	{
		this.sysVersion = sysVersion;
	}

	@Column(name = "version_code", length = 8)
	public String getVersionCode()
	{
		return this.versionCode;
	}

	public void setVersionCode(String versionCode)
	{
		this.versionCode = versionCode;
	}

	@Column(name = "sign", length = 64)
	public String getSign()
	{
		return this.sign;
	}

	public void setSign(String sign)
	{
		this.sign = sign;
	}

	@Column(name = "v", length = 4)
	public String getV()
	{
		return this.v;
	}

	public void setV(String v)
	{
		this.v = v;
	}

	@Column(name = "session_id", length = 64)
	public String getSessionId()
	{
		return this.sessionId;
	}

	public void setSessionId(String sessionId)
	{
		this.sessionId = sessionId;
	}

	@Column(name = "params", length = 65535)
	public String getParams()
	{
		return this.params;
	}

	public void setParams(String params)
	{
		this.params = params;
	}

	@Column(name = "add_date_long", nullable = false)
	public long getAddDateLong()
	{
		return this.addDateLong;
	}

	public void setAddDateLong(long addDateLong)
	{
		this.addDateLong = addDateLong;
	}
}
