package com.bet.orms;
// Generated 2018-3-29 21:47:22 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * CityInfo generated by hbm2java
 */
@Entity
@Table(name = "city_info", uniqueConstraints = { @UniqueConstraint(columnNames = "city_id"), @UniqueConstraint(columnNames = "name") })
@Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
public class CityInfo implements java.io.Serializable
{
	private static final long serialVersionUID = -7653802342866513743L;
	private Integer id;
	private String cityId;
	private String name;
	private String code;
	private String provinceId;

	public CityInfo()
	{
	}

	public CityInfo(String cityId, String name)
	{
		this.cityId = cityId;
		this.name = name;
	}

	public CityInfo(String cityId, String name, String code, String provinceId)
	{
		this.cityId = cityId;
		this.name = name;
		this.code = code;
		this.provinceId = provinceId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "city_id", unique = true, nullable = false, length = 16)
	public String getCityId()
	{
		return this.cityId;
	}

	public void setCityId(String cityId)
	{
		this.cityId = cityId;
	}

	@Column(name = "name", unique = true, nullable = false, length = 32)
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	@Column(name = "code", length = 12)
	public String getCode()
	{
		return this.code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	@Column(name = "province_id", length = 16)
	public String getProvinceId()
	{
		return this.provinceId;
	}

	public void setProvinceId(String provinceId)
	{
		this.provinceId = provinceId;
	}
}
