package com.bet.orms;
// Generated 2018-3-29 21:47:22 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * ClientInfo generated by hbm2java
 */
@Entity
@Table(name = "client_info")
@Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
public class ClientInfo implements java.io.Serializable
{
	private static final long serialVersionUID = 7155759135817965406L;
	private Integer id;
	private String platform;
	private String versionName;
	private int versionCode;
	private String agentId;
	private String debugSignKey;
	private String releaseSignKey;
	private String url;
	private String content;
	private byte status;
	private long addDateLong;
	private long updateDateLong;

	public ClientInfo()
	{
	}

	public ClientInfo(String platform, String versionName, int versionCode, String url, String content, byte status, long addDateLong, long updateDateLong)
	{
		this.platform = platform;
		this.versionName = versionName;
		this.versionCode = versionCode;
		this.url = url;
		this.content = content;
		this.status = status;
		this.addDateLong = addDateLong;
		this.updateDateLong = updateDateLong;
	}

	public ClientInfo(String platform, String versionName, int versionCode, String agentId, String debugSignKey, String releaseSignKey, String url, String content, byte status, long addDateLong,
		long updateDateLong)
	{
		this.platform = platform;
		this.versionName = versionName;
		this.versionCode = versionCode;
		this.agentId = agentId;
		this.debugSignKey = debugSignKey;
		this.releaseSignKey = releaseSignKey;
		this.url = url;
		this.content = content;
		this.status = status;
		this.addDateLong = addDateLong;
		this.updateDateLong = updateDateLong;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "platform", nullable = false, length = 16)
	public String getPlatform()
	{
		return this.platform;
	}

	public void setPlatform(String platform)
	{
		this.platform = platform;
	}

	@Column(name = "version_name", nullable = false, length = 16)
	public String getVersionName()
	{
		return this.versionName;
	}

	public void setVersionName(String versionName)
	{
		this.versionName = versionName;
	}

	@Column(name = "version_code", nullable = false)
	public int getVersionCode()
	{
		return this.versionCode;
	}

	public void setVersionCode(int versionCode)
	{
		this.versionCode = versionCode;
	}

	@Column(name = "agent_id", length = 16)
	public String getAgentId()
	{
		return this.agentId;
	}

	public void setAgentId(String agentId)
	{
		this.agentId = agentId;
	}

	@Column(name = "debug_sign_key", length = 128)
	public String getDebugSignKey()
	{
		return this.debugSignKey;
	}

	public void setDebugSignKey(String debugSignKey)
	{
		this.debugSignKey = debugSignKey;
	}

	@Column(name = "release_sign_key", length = 128)
	public String getReleaseSignKey()
	{
		return this.releaseSignKey;
	}

	public void setReleaseSignKey(String releaseSignKey)
	{
		this.releaseSignKey = releaseSignKey;
	}

	@Column(name = "url", nullable = false, length = 256)
	public String getUrl()
	{
		return this.url;
	}

	public void setUrl(String url)
	{
		this.url = url;
	}

	@Column(name = "content", nullable = false, length = 65535)
	public String getContent()
	{
		return this.content;
	}

	public void setContent(String content)
	{
		this.content = content;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus()
	{
		return this.status;
	}

	public void setStatus(byte status)
	{
		this.status = status;
	}

	@Column(name = "add_date_long", nullable = false)
	public long getAddDateLong()
	{
		return this.addDateLong;
	}

	public void setAddDateLong(long addDateLong)
	{
		this.addDateLong = addDateLong;
	}

	@Column(name = "update_date_long", nullable = false)
	public long getUpdateDateLong()
	{
		return this.updateDateLong;
	}

	public void setUpdateDateLong(long updateDateLong)
	{
		this.updateDateLong = updateDateLong;
	}
}
