package com.bet.orms;
// Generated 2018-3-29 21:47:22 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * ClientBugInfo generated by hbm2java
 */
@Entity
@Table(name = "client_bug_info")
@Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
public class ClientBugInfo implements java.io.Serializable
{
	private static final long serialVersionUID = 1985744732471417770L;
	private Integer id;
	private String userId;
	private String platform;
	private int versionCode;
	private String sysVersion;
	private String deviceName;
	private String content;
	private String url;
	private byte status;
	private long addDateLong;

	public ClientBugInfo()
	{
	}

	public ClientBugInfo(String platform, int versionCode, String sysVersion, String deviceName, String content, byte status, long addDateLong)
	{
		this.platform = platform;
		this.versionCode = versionCode;
		this.sysVersion = sysVersion;
		this.deviceName = deviceName;
		this.content = content;
		this.status = status;
		this.addDateLong = addDateLong;
	}

	public ClientBugInfo(String userId, String platform, int versionCode, String sysVersion, String deviceName, String content, String url, byte status, long addDateLong)
	{
		this.userId = userId;
		this.platform = platform;
		this.versionCode = versionCode;
		this.sysVersion = sysVersion;
		this.deviceName = deviceName;
		this.content = content;
		this.url = url;
		this.status = status;
		this.addDateLong = addDateLong;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "user_id", length = 16)
	public String getUserId()
	{
		return this.userId;
	}

	public void setUserId(String userId)
	{
		this.userId = userId;
	}

	@Column(name = "platform", nullable = false, length = 16)
	public String getPlatform()
	{
		return this.platform;
	}

	public void setPlatform(String platform)
	{
		this.platform = platform;
	}

	@Column(name = "version_code", nullable = false)
	public int getVersionCode()
	{
		return this.versionCode;
	}

	public void setVersionCode(int versionCode)
	{
		this.versionCode = versionCode;
	}

	@Column(name = "sys_version", nullable = false, length = 32)
	public String getSysVersion()
	{
		return this.sysVersion;
	}

	public void setSysVersion(String sysVersion)
	{
		this.sysVersion = sysVersion;
	}

	@Column(name = "device_name", nullable = false, length = 32)
	public String getDeviceName()
	{
		return this.deviceName;
	}

	public void setDeviceName(String deviceName)
	{
		this.deviceName = deviceName;
	}

	@Column(name = "content", nullable = false, length = 65535)
	public String getContent()
	{
		return this.content;
	}

	public void setContent(String content)
	{
		this.content = content;
	}

	@Column(name = "url", length = 1024)
	public String getUrl()
	{
		return this.url;
	}

	public void setUrl(String url)
	{
		this.url = url;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus()
	{
		return this.status;
	}

	public void setStatus(byte status)
	{
		this.status = status;
	}

	@Column(name = "add_date_long", nullable = false)
	public long getAddDateLong()
	{
		return this.addDateLong;
	}

	public void setAddDateLong(long addDateLong)
	{
		this.addDateLong = addDateLong;
	}
}
