package com.bet.orms;
// Generated 2018-3-29 21:47:22 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * ConfigInfo generated by hbm2java
 */
@Entity
@Table(name = "config_info", uniqueConstraints = { @UniqueConstraint(columnNames = "config_id"), @UniqueConstraint(columnNames = "config_name") })
@Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
public class ConfigInfo implements java.io.Serializable
{
	private static final long serialVersionUID = -1462335100499333482L;
	private Integer id;
	private String configId;
	private String configName;
	private String content;
	private byte status;
	private String remark;

	public ConfigInfo()
	{
	}

	public ConfigInfo(String configId, String configName, String content, byte status)
	{
		this.configId = configId;
		this.configName = configName;
		this.content = content;
		this.status = status;
	}

	public ConfigInfo(String configId, String configName, String content, byte status, String remark)
	{
		this.configId = configId;
		this.configName = configName;
		this.content = content;
		this.status = status;
		this.remark = remark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "config_id", unique = true, nullable = false, length = 32)
	public String getConfigId()
	{
		return this.configId;
	}

	public void setConfigId(String configId)
	{
		this.configId = configId;
	}

	@Column(name = "config_name", unique = true, nullable = false, length = 32)
	public String getConfigName()
	{
		return this.configName;
	}

	public void setConfigName(String configName)
	{
		this.configName = configName;
	}

	@Column(name = "content", nullable = false, length = 1024)
	public String getContent()
	{
		return this.content;
	}

	public void setContent(String content)
	{
		this.content = content;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus()
	{
		return this.status;
	}

	public void setStatus(byte status)
	{
		this.status = status;
	}

	@Column(name = "remark", length = 256)
	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}
}
