package com.bet.orms;
// Generated 2018-4-27 17:27:01 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * DayUserStatisticsLogInfo generated by hbm2java
 */
@Entity
@Table(name = "day_user_statistics_log_info", uniqueConstraints = @UniqueConstraint(columnNames = "log_id"))
@Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
public class DayUserStatisticsLogInfo implements java.io.Serializable
{
	private static final long serialVersionUID = -1384093941931501733L;
	private Integer id;
	private String logId;
	private String dayId;
	private String userId;
	private long userBetMoney;
	private long userRechargeMoney;
	private long userWithdrawMoney;
	private long finalBonusMoney;
	private long halfBonusMoney;
	private long countBonusMoney;
	private long shareBonusMoney;
	private long agentBonusMoney;
	private long sameLevel1BonusMoney;
	private long sameLevel2BonusMoney;
	private long benefitBonusMoney;
	private long teamMoney;
	private byte status;
	private long addDateLong;
	private long updateDateLong;

	public DayUserStatisticsLogInfo()
	{
	}

	public DayUserStatisticsLogInfo(String logId, String dayId, String userId, long userBetMoney, long userRechargeMoney, long userWithdrawMoney, long finalBonusMoney, long halfBonusMoney,
		long countBonusMoney, long shareBonusMoney, long agentBonusMoney, long sameLevel1BonusMoney, long sameLevel2BonusMoney, long benefitBonusMoney, long teamMoney, byte status, long addDateLong,
		long updateDateLong)
	{
		this.logId = logId;
		this.dayId = dayId;
		this.userId = userId;
		this.userBetMoney = userBetMoney;
		this.userRechargeMoney = userRechargeMoney;
		this.userWithdrawMoney = userWithdrawMoney;
		this.finalBonusMoney = finalBonusMoney;
		this.halfBonusMoney = halfBonusMoney;
		this.countBonusMoney = countBonusMoney;
		this.shareBonusMoney = shareBonusMoney;
		this.agentBonusMoney = agentBonusMoney;
		this.sameLevel1BonusMoney = sameLevel1BonusMoney;
		this.sameLevel2BonusMoney = sameLevel2BonusMoney;
		this.benefitBonusMoney = benefitBonusMoney;
		this.teamMoney = teamMoney;
		this.status = status;
		this.addDateLong = addDateLong;
		this.updateDateLong = updateDateLong;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "log_id", unique = true, nullable = false, length = 16)
	public String getLogId()
	{
		return this.logId;
	}

	public void setLogId(String logId)
	{
		this.logId = logId;
	}

	@Column(name = "day_id", nullable = false, length = 16)
	public String getDayId()
	{
		return this.dayId;
	}

	public void setDayId(String dayId)
	{
		this.dayId = dayId;
	}

	@Column(name = "user_id", nullable = false, length = 16)
	public String getUserId()
	{
		return this.userId;
	}

	public void setUserId(String userId)
	{
		this.userId = userId;
	}

	@Column(name = "user_bet_money", nullable = false)
	public long getUserBetMoney()
	{
		return this.userBetMoney;
	}

	public void setUserBetMoney(long userBetMoney)
	{
		this.userBetMoney = userBetMoney;
	}

	@Column(name = "user_recharge_money", nullable = false)
	public long getUserRechargeMoney()
	{
		return this.userRechargeMoney;
	}

	public void setUserRechargeMoney(long userRechargeMoney)
	{
		this.userRechargeMoney = userRechargeMoney;
	}

	@Column(name = "user_withdraw_money", nullable = false)
	public long getUserWithdrawMoney()
	{
		return this.userWithdrawMoney;
	}

	public void setUserWithdrawMoney(long userWithdrawMoney)
	{
		this.userWithdrawMoney = userWithdrawMoney;
	}

	@Column(name = "final_bonus_money", nullable = false)
	public long getFinalBonusMoney()
	{
		return this.finalBonusMoney;
	}

	public void setFinalBonusMoney(long finalBonusMoney)
	{
		this.finalBonusMoney = finalBonusMoney;
	}

	@Column(name = "half_bonus_money", nullable = false)
	public long getHalfBonusMoney()
	{
		return this.halfBonusMoney;
	}

	public void setHalfBonusMoney(long halfBonusMoney)
	{
		this.halfBonusMoney = halfBonusMoney;
	}

	@Column(name = "count_bonus_money", nullable = false)
	public long getCountBonusMoney()
	{
		return this.countBonusMoney;
	}

	public void setCountBonusMoney(long countBonusMoney)
	{
		this.countBonusMoney = countBonusMoney;
	}

	@Column(name = "share_bonus_money", nullable = false)
	public long getShareBonusMoney()
	{
		return this.shareBonusMoney;
	}

	public void setShareBonusMoney(long shareBonusMoney)
	{
		this.shareBonusMoney = shareBonusMoney;
	}

	@Column(name = "agent_bonus_money", nullable = false)
	public long getAgentBonusMoney()
	{
		return this.agentBonusMoney;
	}

	public void setAgentBonusMoney(long agentBonusMoney)
	{
		this.agentBonusMoney = agentBonusMoney;
	}

	@Column(name = "same_level1_bonus_money", nullable = false)
	public long getSameLevel1BonusMoney()
	{
		return this.sameLevel1BonusMoney;
	}

	public void setSameLevel1BonusMoney(long sameLevel1BonusMoney)
	{
		this.sameLevel1BonusMoney = sameLevel1BonusMoney;
	}

	@Column(name = "same_level2_bonus_money", nullable = false)
	public long getSameLevel2BonusMoney()
	{
		return this.sameLevel2BonusMoney;
	}

	public void setSameLevel2BonusMoney(long sameLevel2BonusMoney)
	{
		this.sameLevel2BonusMoney = sameLevel2BonusMoney;
	}

	@Column(name = "benefit_bonus_money", nullable = false)
	public long getBenefitBonusMoney()
	{
		return this.benefitBonusMoney;
	}

	public void setBenefitBonusMoney(long benefitBonusMoney)
	{
		this.benefitBonusMoney = benefitBonusMoney;
	}

	@Column(name = "team_money", nullable = false)
	public long getTeamMoney()
	{
		return this.teamMoney;
	}

	public void setTeamMoney(long teamMoney)
	{
		this.teamMoney = teamMoney;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus()
	{
		return this.status;
	}

	public void setStatus(byte status)
	{
		this.status = status;
	}

	@Column(name = "add_date_long", nullable = false)
	public long getAddDateLong()
	{
		return this.addDateLong;
	}

	public void setAddDateLong(long addDateLong)
	{
		this.addDateLong = addDateLong;
	}

	@Column(name = "update_date_long", nullable = false)
	public long getUpdateDateLong()
	{
		return this.updateDateLong;
	}

	public void setUpdateDateLong(long updateDateLong)
	{
		this.updateDateLong = updateDateLong;
	}
}
