package com.bet.orms;
// Generated 2018-3-29 21:47:22 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * DistrictInfo generated by hbm2java
 */
@Entity
@Table(name = "district_info", uniqueConstraints = @UniqueConstraint(columnNames = "district_id"))
@Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
public class DistrictInfo implements java.io.Serializable
{
	private static final long serialVersionUID = 5851288833523897892L;
	private Integer id;
	private String districtId;
	private String name;
	private String code;
	private String provinceId;
	private String cityId;

	public DistrictInfo()
	{
	}

	public DistrictInfo(String districtId, String name)
	{
		this.districtId = districtId;
		this.name = name;
	}

	public DistrictInfo(String districtId, String name, String code, String provinceId, String cityId)
	{
		this.districtId = districtId;
		this.name = name;
		this.code = code;
		this.provinceId = provinceId;
		this.cityId = cityId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "district_id", unique = true, nullable = false, length = 16)
	public String getDistrictId()
	{
		return this.districtId;
	}

	public void setDistrictId(String districtId)
	{
		this.districtId = districtId;
	}

	@Column(name = "name", nullable = false, length = 32)
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	@Column(name = "code", length = 12)
	public String getCode()
	{
		return this.code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	@Column(name = "province_id", length = 16)
	public String getProvinceId()
	{
		return this.provinceId;
	}

	public void setProvinceId(String provinceId)
	{
		this.provinceId = provinceId;
	}

	@Column(name = "city_id", length = 16)
	public String getCityId()
	{
		return this.cityId;
	}

	public void setCityId(String cityId)
	{
		this.cityId = cityId;
	}
}
