package com.bet.orms;
// Generated 2018-5-2 14:28:22 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * MatchInfo generated by hbm2java
 */
@Entity
@Table(name = "match_info", uniqueConstraints = { @UniqueConstraint(columnNames = "out_id"), @UniqueConstraint(columnNames = "phase_id") })
@Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
public class MatchInfo implements java.io.Serializable
{
	private static final long serialVersionUID = -2532753198974368105L;
	private Integer id;
	private String phaseId;
	private String outId;
	private String matchName;
	private String matchNum;
	private long matchDate;
	private long timeEndsale;
	private String homeTeamId;
	private String homeTeam;
	private String homeTeamPicUrl;
	private String awayTeamId;
	private String awayTeam;
	private String awayTeamPicUrl;
	private String videoUrl;
	private Byte finalScore1;
	private Byte finalScore2;
	private Long updateFinalScoreDateLong;
	private Byte halfScore1;
	private Byte halfScore2;
	private Long updateHalfScoreDateLong;
	private String handicap;
	private byte halfResultStatus;
	private byte finalResultStatus;
	private byte halfProfitStatus;
	private byte finalProfitStatus;
	private byte leaderProfitStatus;
	private int sortIndex;
	private byte status;
	private long addDateLong;
	private long updateDateLong;

	public MatchInfo()
	{
	}

	public MatchInfo(String phaseId, String matchName, long matchDate, long timeEndsale, String homeTeamId, String homeTeam, String awayTeamId, String awayTeam, byte halfResultStatus,
		byte finalResultStatus, byte halfProfitStatus, byte finalProfitStatus, byte leaderProfitStatus, int sortIndex, byte status, long addDateLong, long updateDateLong)
	{
		this.phaseId = phaseId;
		this.matchName = matchName;
		this.matchDate = matchDate;
		this.timeEndsale = timeEndsale;
		this.homeTeamId = homeTeamId;
		this.homeTeam = homeTeam;
		this.awayTeamId = awayTeamId;
		this.awayTeam = awayTeam;
		this.halfResultStatus = halfResultStatus;
		this.finalResultStatus = finalResultStatus;
		this.halfProfitStatus = halfProfitStatus;
		this.finalProfitStatus = finalProfitStatus;
		this.leaderProfitStatus = leaderProfitStatus;
		this.sortIndex = sortIndex;
		this.status = status;
		this.addDateLong = addDateLong;
		this.updateDateLong = updateDateLong;
	}

	public MatchInfo(String phaseId, String outId, String matchName, String matchNum, long matchDate, long timeEndsale, String homeTeamId, String homeTeam, String homeTeamPicUrl, String awayTeamId,
		String awayTeam, String awayTeamPicUrl, String videoUrl, Byte finalScore1, Byte finalScore2, Long updateFinalScoreDateLong, Byte halfScore1, Byte halfScore2, Long updateHalfScoreDateLong,
		String handicap, byte halfResultStatus, byte finalResultStatus, byte halfProfitStatus, byte finalProfitStatus, byte leaderProfitStatus, int sortIndex, byte status, long addDateLong,
		long updateDateLong)
	{
		this.phaseId = phaseId;
		this.outId = outId;
		this.matchName = matchName;
		this.matchNum = matchNum;
		this.matchDate = matchDate;
		this.timeEndsale = timeEndsale;
		this.homeTeamId = homeTeamId;
		this.homeTeam = homeTeam;
		this.homeTeamPicUrl = homeTeamPicUrl;
		this.awayTeamId = awayTeamId;
		this.awayTeam = awayTeam;
		this.awayTeamPicUrl = awayTeamPicUrl;
		this.videoUrl = videoUrl;
		this.finalScore1 = finalScore1;
		this.finalScore2 = finalScore2;
		this.updateFinalScoreDateLong = updateFinalScoreDateLong;
		this.halfScore1 = halfScore1;
		this.halfScore2 = halfScore2;
		this.updateHalfScoreDateLong = updateHalfScoreDateLong;
		this.handicap = handicap;
		this.halfResultStatus = halfResultStatus;
		this.finalResultStatus = finalResultStatus;
		this.halfProfitStatus = halfProfitStatus;
		this.finalProfitStatus = finalProfitStatus;
		this.leaderProfitStatus = leaderProfitStatus;
		this.sortIndex = sortIndex;
		this.status = status;
		this.addDateLong = addDateLong;
		this.updateDateLong = updateDateLong;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "phase_id", unique = true, nullable = false, length = 16)
	public String getPhaseId()
	{
		return this.phaseId;
	}

	public void setPhaseId(String phaseId)
	{
		this.phaseId = phaseId;
	}

	@Column(name = "out_id", unique = true, length = 32)
	public String getOutId()
	{
		return this.outId;
	}

	public void setOutId(String outId)
	{
		this.outId = outId;
	}

	@Column(name = "match_name", nullable = false, length = 64)
	public String getMatchName()
	{
		return this.matchName;
	}

	public void setMatchName(String matchName)
	{
		this.matchName = matchName;
	}

	@Column(name = "match_num", length = 16)
	public String getMatchNum()
	{
		return this.matchNum;
	}

	public void setMatchNum(String matchNum)
	{
		this.matchNum = matchNum;
	}

	@Column(name = "match_date", nullable = false)
	public long getMatchDate()
	{
		return this.matchDate;
	}

	public void setMatchDate(long matchDate)
	{
		this.matchDate = matchDate;
	}

	@Column(name = "time_endsale", nullable = false)
	public long getTimeEndsale()
	{
		return this.timeEndsale;
	}

	public void setTimeEndsale(long timeEndsale)
	{
		this.timeEndsale = timeEndsale;
	}

	@Column(name = "home_team_id", nullable = false, length = 16)
	public String getHomeTeamId()
	{
		return this.homeTeamId;
	}

	public void setHomeTeamId(String homeTeamId)
	{
		this.homeTeamId = homeTeamId;
	}

	@Column(name = "home_team", nullable = false, length = 32)
	public String getHomeTeam()
	{
		return this.homeTeam;
	}

	public void setHomeTeam(String homeTeam)
	{
		this.homeTeam = homeTeam;
	}

	@Column(name = "home_team_pic_url", length = 128)
	public String getHomeTeamPicUrl()
	{
		return this.homeTeamPicUrl;
	}

	public void setHomeTeamPicUrl(String homeTeamPicUrl)
	{
		this.homeTeamPicUrl = homeTeamPicUrl;
	}

	@Column(name = "away_team_id", nullable = false, length = 16)
	public String getAwayTeamId()
	{
		return this.awayTeamId;
	}

	public void setAwayTeamId(String awayTeamId)
	{
		this.awayTeamId = awayTeamId;
	}

	@Column(name = "away_team", nullable = false, length = 32)
	public String getAwayTeam()
	{
		return this.awayTeam;
	}

	public void setAwayTeam(String awayTeam)
	{
		this.awayTeam = awayTeam;
	}

	@Column(name = "away_team_pic_url", length = 128)
	public String getAwayTeamPicUrl()
	{
		return this.awayTeamPicUrl;
	}

	public void setAwayTeamPicUrl(String awayTeamPicUrl)
	{
		this.awayTeamPicUrl = awayTeamPicUrl;
	}

	@Column(name = "video_url", length = 256)
	public String getVideoUrl()
	{
		return this.videoUrl;
	}

	public void setVideoUrl(String videoUrl)
	{
		this.videoUrl = videoUrl;
	}

	@Column(name = "final_score1")
	public Byte getFinalScore1()
	{
		return this.finalScore1;
	}

	public void setFinalScore1(Byte finalScore1)
	{
		this.finalScore1 = finalScore1;
	}

	@Column(name = "final_score2")
	public Byte getFinalScore2()
	{
		return this.finalScore2;
	}

	public void setFinalScore2(Byte finalScore2)
	{
		this.finalScore2 = finalScore2;
	}

	@Column(name = "update_final_score_date_long")
	public Long getUpdateFinalScoreDateLong()
	{
		return this.updateFinalScoreDateLong;
	}

	public void setUpdateFinalScoreDateLong(Long updateFinalScoreDateLong)
	{
		this.updateFinalScoreDateLong = updateFinalScoreDateLong;
	}

	@Column(name = "half_score1")
	public Byte getHalfScore1()
	{
		return this.halfScore1;
	}

	public void setHalfScore1(Byte halfScore1)
	{
		this.halfScore1 = halfScore1;
	}

	@Column(name = "half_score2")
	public Byte getHalfScore2()
	{
		return this.halfScore2;
	}

	public void setHalfScore2(Byte halfScore2)
	{
		this.halfScore2 = halfScore2;
	}

	@Column(name = "update_half_score_date_long")
	public Long getUpdateHalfScoreDateLong()
	{
		return this.updateHalfScoreDateLong;
	}

	public void setUpdateHalfScoreDateLong(Long updateHalfScoreDateLong)
	{
		this.updateHalfScoreDateLong = updateHalfScoreDateLong;
	}

	@Column(name = "handicap", length = 2)
	public String getHandicap()
	{
		return this.handicap;
	}

	public void setHandicap(String handicap)
	{
		this.handicap = handicap;
	}

	@Column(name = "half_result_status", nullable = false)
	public byte getHalfResultStatus()
	{
		return this.halfResultStatus;
	}

	public void setHalfResultStatus(byte halfResultStatus)
	{
		this.halfResultStatus = halfResultStatus;
	}

	@Column(name = "final_result_status", nullable = false)
	public byte getFinalResultStatus()
	{
		return this.finalResultStatus;
	}

	public void setFinalResultStatus(byte finalResultStatus)
	{
		this.finalResultStatus = finalResultStatus;
	}

	@Column(name = "half_profit_status", nullable = false)
	public byte getHalfProfitStatus()
	{
		return this.halfProfitStatus;
	}

	public void setHalfProfitStatus(byte halfProfitStatus)
	{
		this.halfProfitStatus = halfProfitStatus;
	}

	@Column(name = "final_profit_status", nullable = false)
	public byte getFinalProfitStatus()
	{
		return this.finalProfitStatus;
	}

	public void setFinalProfitStatus(byte finalProfitStatus)
	{
		this.finalProfitStatus = finalProfitStatus;
	}

	@Column(name = "leader_profit_status", nullable = false)
	public byte getLeaderProfitStatus()
	{
		return this.leaderProfitStatus;
	}

	public void setLeaderProfitStatus(byte leaderProfitStatus)
	{
		this.leaderProfitStatus = leaderProfitStatus;
	}

	@Column(name = "sort_index", nullable = false)
	public int getSortIndex()
	{
		return this.sortIndex;
	}

	public void setSortIndex(int sortIndex)
	{
		this.sortIndex = sortIndex;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus()
	{
		return this.status;
	}

	public void setStatus(byte status)
	{
		this.status = status;
	}

	@Column(name = "add_date_long", nullable = false)
	public long getAddDateLong()
	{
		return this.addDateLong;
	}

	public void setAddDateLong(long addDateLong)
	{
		this.addDateLong = addDateLong;
	}

	@Column(name = "update_date_long", nullable = false)
	public long getUpdateDateLong()
	{
		return this.updateDateLong;
	}

	public void setUpdateDateLong(long updateDateLong)
	{
		this.updateDateLong = updateDateLong;
	}
}
