package com.bet.orms;
// Generated 2018-4-12 22:01:22 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * MinlePayNotifyLogInfo generated by hbm2java
 */
@Entity
@Table(name = "minle_pay_notify_log_info", uniqueConstraints = @UniqueConstraint(columnNames = "notify_id"))
@Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
public class MinlePayNotifyLogInfo implements java.io.Serializable
{
	private static final long serialVersionUID = -7637119649223468020L;
	private Integer id;
	private String notifyId;
	private String errorCode;
	private String errorMsg;
	private String sign;
	private String payStatus;
	private String outTradeNo;
	private String orderId;
	private String totalFee;
	private String body;
	private byte status;
	private long addDateLong;
	private long updateDateLong;

	public MinlePayNotifyLogInfo()
	{
	}

	public MinlePayNotifyLogInfo(String notifyId, byte status, long addDateLong, long updateDateLong)
	{
		this.notifyId = notifyId;
		this.status = status;
		this.addDateLong = addDateLong;
		this.updateDateLong = updateDateLong;
	}

	public MinlePayNotifyLogInfo(String notifyId, String errorCode, String errorMsg, String sign, String payStatus, String outTradeNo, String orderId, String totalFee, String body, byte status,
		long addDateLong, long updateDateLong)
	{
		this.notifyId = notifyId;
		this.errorCode = errorCode;
		this.errorMsg = errorMsg;
		this.sign = sign;
		this.payStatus = payStatus;
		this.outTradeNo = outTradeNo;
		this.orderId = orderId;
		this.totalFee = totalFee;
		this.body = body;
		this.status = status;
		this.addDateLong = addDateLong;
		this.updateDateLong = updateDateLong;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "notify_id", unique = true, nullable = false, length = 16)
	public String getNotifyId()
	{
		return this.notifyId;
	}

	public void setNotifyId(String notifyId)
	{
		this.notifyId = notifyId;
	}

	@Column(name = "error_code", length = 8)
	public String getErrorCode()
	{
		return this.errorCode;
	}

	public void setErrorCode(String errorCode)
	{
		this.errorCode = errorCode;
	}

	@Column(name = "error_msg", length = 512)
	public String getErrorMsg()
	{
		return this.errorMsg;
	}

	public void setErrorMsg(String errorMsg)
	{
		this.errorMsg = errorMsg;
	}

	@Column(name = "sign", length = 32)
	public String getSign()
	{
		return this.sign;
	}

	public void setSign(String sign)
	{
		this.sign = sign;
	}

	@Column(name = "pay_status", length = 32)
	public String getPayStatus()
	{
		return this.payStatus;
	}

	public void setPayStatus(String payStatus)
	{
		this.payStatus = payStatus;
	}

	@Column(name = "out_trade_no", length = 32)
	public String getOutTradeNo()
	{
		return this.outTradeNo;
	}

	public void setOutTradeNo(String outTradeNo)
	{
		this.outTradeNo = outTradeNo;
	}

	@Column(name = "order_id", length = 64)
	public String getOrderId()
	{
		return this.orderId;
	}

	public void setOrderId(String orderId)
	{
		this.orderId = orderId;
	}

	@Column(name = "total_fee", length = 8)
	public String getTotalFee()
	{
		return this.totalFee;
	}

	public void setTotalFee(String totalFee)
	{
		this.totalFee = totalFee;
	}

	@Column(name = "body", length = 256)
	public String getBody()
	{
		return this.body;
	}

	public void setBody(String body)
	{
		this.body = body;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus()
	{
		return this.status;
	}

	public void setStatus(byte status)
	{
		this.status = status;
	}

	@Column(name = "add_date_long", nullable = false)
	public long getAddDateLong()
	{
		return this.addDateLong;
	}

	public void setAddDateLong(long addDateLong)
	{
		this.addDateLong = addDateLong;
	}

	@Column(name = "update_date_long", nullable = false)
	public long getUpdateDateLong()
	{
		return this.updateDateLong;
	}

	public void setUpdateDateLong(long updateDateLong)
	{
		this.updateDateLong = updateDateLong;
	}
}
