package com.bet.orms;
// Generated 2018-5-2 15:36:32 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * MsgInfo generated by hbm2java
 */
@Entity
@Table(name = "msg_info", uniqueConstraints = @UniqueConstraint(columnNames = "msg_id"))
@Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
public class MsgInfo implements java.io.Serializable
{
	private static final long serialVersionUID = -7455577893319755444L;
	private Integer id;
	private String msgId;
	private String sortId;
	private String title;
	private String userId;
	private String shortContent;
	private byte status;
	private long addDateLong;
	private long updateDateLong;

	public MsgInfo()
	{
	}

	public MsgInfo(String msgId, String sortId, String title, String userId, String shortContent, byte status, long addDateLong, long updateDateLong)
	{
		this.msgId = msgId;
		this.sortId = sortId;
		this.title = title;
		this.userId = userId;
		this.shortContent = shortContent;
		this.status = status;
		this.addDateLong = addDateLong;
		this.updateDateLong = updateDateLong;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "msg_id", unique = true, nullable = false, length = 16)
	public String getMsgId()
	{
		return this.msgId;
	}

	public void setMsgId(String msgId)
	{
		this.msgId = msgId;
	}

	@Column(name = "sort_id", nullable = false, length = 16)
	public String getSortId()
	{
		return this.sortId;
	}

	public void setSortId(String sortId)
	{
		this.sortId = sortId;
	}

	@Column(name = "title", nullable = false, length = 64)
	public String getTitle()
	{
		return this.title;
	}

	public void setTitle(String title)
	{
		this.title = title;
	}

	@Column(name = "user_id", nullable = false, length = 16)
	public String getUserId()
	{
		return this.userId;
	}

	public void setUserId(String userId)
	{
		this.userId = userId;
	}

	@Column(name = "short_content", nullable = false, length = 128)
	public String getShortContent()
	{
		return this.shortContent;
	}

	public void setShortContent(String shortContent)
	{
		this.shortContent = shortContent;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus()
	{
		return this.status;
	}

	public void setStatus(byte status)
	{
		this.status = status;
	}

	@Column(name = "add_date_long", nullable = false)
	public long getAddDateLong()
	{
		return this.addDateLong;
	}

	public void setAddDateLong(long addDateLong)
	{
		this.addDateLong = addDateLong;
	}

	@Column(name = "update_date_long", nullable = false)
	public long getUpdateDateLong()
	{
		return this.updateDateLong;
	}

	public void setUpdateDateLong(long updateDateLong)
	{
		this.updateDateLong = updateDateLong;
	}
}
