package com.bet.orms;
// Generated 2018-3-29 21:47:22 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * NewsSortInfo generated by hbm2java
 */
@Entity
@Table(name = "news_sort_info", uniqueConstraints = { @UniqueConstraint(columnNames = "name"), @UniqueConstraint(columnNames = "sort_id") })
@Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
public class NewsSortInfo implements java.io.Serializable
{
	private static final long serialVersionUID = 597027427434482116L;
	private Integer id;
	private String sortId;
	private String name;
	private String parentId;
	private byte levelId;
	private byte status;

	public NewsSortInfo()
	{
	}

	public NewsSortInfo(String sortId, String name, byte levelId, byte status)
	{
		this.sortId = sortId;
		this.name = name;
		this.levelId = levelId;
		this.status = status;
	}

	public NewsSortInfo(String sortId, String name, String parentId, byte levelId, byte status)
	{
		this.sortId = sortId;
		this.name = name;
		this.parentId = parentId;
		this.levelId = levelId;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "sort_id", unique = true, nullable = false, length = 16)
	public String getSortId()
	{
		return this.sortId;
	}

	public void setSortId(String sortId)
	{
		this.sortId = sortId;
	}

	@Column(name = "name", unique = true, nullable = false, length = 32)
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	@Column(name = "parent_id", length = 16)
	public String getParentId()
	{
		return this.parentId;
	}

	public void setParentId(String parentId)
	{
		this.parentId = parentId;
	}

	@Column(name = "level_id", nullable = false)
	public byte getLevelId()
	{
		return this.levelId;
	}

	public void setLevelId(byte levelId)
	{
		this.levelId = levelId;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus()
	{
		return this.status;
	}

	public void setStatus(byte status)
	{
		this.status = status;
	}
}
