package com.bet.orms;
// Generated 2018-4-4 15:54:13 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * NewsInfo generated by hbm2java
 */
@Entity
@Table(name = "news_info", uniqueConstraints = @UniqueConstraint(columnNames = "news_id"))
@Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
public class NewsInfo implements java.io.Serializable
{
	private static final long serialVersionUID = -7740849795039424572L;
	private Integer id;
	private String newsId;
	private String sortId;
	private String title;
	private String author;
	private String shortContent;
	private String content;
	private byte topStatus;
	private byte status;
	private Long valideDateLong;
	private long addDateLong;
	private long updateDateLong;

	public NewsInfo()
	{
	}

	public NewsInfo(String newsId, String sortId, String title, String author, String shortContent, String content, byte topStatus, byte status, long addDateLong, long updateDateLong)
	{
		this.newsId = newsId;
		this.sortId = sortId;
		this.title = title;
		this.author = author;
		this.shortContent = shortContent;
		this.content = content;
		this.topStatus = topStatus;
		this.status = status;
		this.addDateLong = addDateLong;
		this.updateDateLong = updateDateLong;
	}

	public NewsInfo(String newsId, String sortId, String title, String author, String shortContent, String content, byte topStatus, byte status, Long valideDateLong, long addDateLong,
		long updateDateLong)
	{
		this.newsId = newsId;
		this.sortId = sortId;
		this.title = title;
		this.author = author;
		this.shortContent = shortContent;
		this.content = content;
		this.topStatus = topStatus;
		this.status = status;
		this.valideDateLong = valideDateLong;
		this.addDateLong = addDateLong;
		this.updateDateLong = updateDateLong;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "news_id", unique = true, nullable = false, length = 16)
	public String getNewsId()
	{
		return this.newsId;
	}

	public void setNewsId(String newsId)
	{
		this.newsId = newsId;
	}

	@Column(name = "sort_id", nullable = false, length = 16)
	public String getSortId()
	{
		return this.sortId;
	}

	public void setSortId(String sortId)
	{
		this.sortId = sortId;
	}

	@Column(name = "title", nullable = false, length = 64)
	public String getTitle()
	{
		return this.title;
	}

	public void setTitle(String title)
	{
		this.title = title;
	}

	@Column(name = "author", nullable = false, length = 32)
	public String getAuthor()
	{
		return this.author;
	}

	public void setAuthor(String author)
	{
		this.author = author;
	}

	@Column(name = "short_content", nullable = false, length = 128)
	public String getShortContent()
	{
		return this.shortContent;
	}

	public void setShortContent(String shortContent)
	{
		this.shortContent = shortContent;
	}

	@Column(name = "content", nullable = false, length = 65535)
	public String getContent()
	{
		return this.content;
	}

	public void setContent(String content)
	{
		this.content = content;
	}

	@Column(name = "top_status", nullable = false)
	public byte getTopStatus()
	{
		return this.topStatus;
	}

	public void setTopStatus(byte topStatus)
	{
		this.topStatus = topStatus;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus()
	{
		return this.status;
	}

	public void setStatus(byte status)
	{
		this.status = status;
	}

	@Column(name = "valide_date_long")
	public Long getValideDateLong()
	{
		return this.valideDateLong;
	}

	public void setValideDateLong(Long valideDateLong)
	{
		this.valideDateLong = valideDateLong;
	}

	@Column(name = "add_date_long", nullable = false)
	public long getAddDateLong()
	{
		return this.addDateLong;
	}

	public void setAddDateLong(long addDateLong)
	{
		this.addDateLong = addDateLong;
	}

	@Column(name = "update_date_long", nullable = false)
	public long getUpdateDateLong()
	{
		return this.updateDateLong;
	}

	public void setUpdateDateLong(long updateDateLong)
	{
		this.updateDateLong = updateDateLong;
	}
}
