package com.bet.orms;
// Generated 2018-4-11 21:48:44 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * PayConfigInfo generated by hbm2java
 */
@Entity
@Table(name = "pay_config_info", uniqueConstraints = @UniqueConstraint(columnNames = "config_id"))
@Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
public class PayConfigInfo implements java.io.Serializable
{
	private static final long serialVersionUID = -8913339753690929000L;
	private Integer id;
	private String configId;
	private String platform;
	private String mchId;
	private String payKey;
	private int sortIndex;
	private byte status;
	private long addDateLong;
	private long updateDateLong;

	public PayConfigInfo()
	{
	}

	public PayConfigInfo(String configId, String platform, String mchId, String payKey, int sortIndex, byte status, long addDateLong, long updateDateLong)
	{
		this.configId = configId;
		this.platform = platform;
		this.mchId = mchId;
		this.payKey = payKey;
		this.sortIndex = sortIndex;
		this.status = status;
		this.addDateLong = addDateLong;
		this.updateDateLong = updateDateLong;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "config_id", unique = true, nullable = false, length = 16)
	public String getConfigId()
	{
		return this.configId;
	}

	public void setConfigId(String configId)
	{
		this.configId = configId;
	}

	@Column(name = "platform", nullable = false, length = 32)
	public String getPlatform()
	{
		return this.platform;
	}

	public void setPlatform(String platform)
	{
		this.platform = platform;
	}

	@Column(name = "mch_id", nullable = false, length = 32)
	public String getMchId()
	{
		return this.mchId;
	}

	public void setMchId(String mchId)
	{
		this.mchId = mchId;
	}

	@Column(name = "pay_key", nullable = false, length = 32)
	public String getPayKey()
	{
		return this.payKey;
	}

	public void setPayKey(String payKey)
	{
		this.payKey = payKey;
	}

	@Column(name = "sort_index", nullable = false)
	public int getSortIndex()
	{
		return this.sortIndex;
	}

	public void setSortIndex(int sortIndex)
	{
		this.sortIndex = sortIndex;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus()
	{
		return this.status;
	}

	public void setStatus(byte status)
	{
		this.status = status;
	}

	@Column(name = "add_date_long", nullable = false)
	public long getAddDateLong()
	{
		return this.addDateLong;
	}

	public void setAddDateLong(long addDateLong)
	{
		this.addDateLong = addDateLong;
	}

	@Column(name = "update_date_long", nullable = false)
	public long getUpdateDateLong()
	{
		return this.updateDateLong;
	}

	public void setUpdateDateLong(long updateDateLong)
	{
		this.updateDateLong = updateDateLong;
	}
}
