package com.bet.orms;
// Generated 2018-4-8 9:49:06 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * PayeeInfo generated by hbm2java
 */
@Entity
@Table(name = "payee_info", uniqueConstraints = @UniqueConstraint(columnNames = "payee_id"))
@Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
public class PayeeInfo implements java.io.Serializable
{
	private static final long serialVersionUID = 8688651271400368238L;
	private Integer id;
	private String payeeId;
	private String payeeName;
	private String bankName;
	private String bankCardId;
	private String picUrl;
	private String type;
	private int sortIndex;
	private byte status;
	private long addDateLong;
	private long updateDateLong;

	public PayeeInfo()
	{
	}

	public PayeeInfo(String payeeId, String payeeName, String bankName, String bankCardId, int sortIndex, byte status, long addDateLong, long updateDateLong)
	{
		this.payeeId = payeeId;
		this.payeeName = payeeName;
		this.bankName = bankName;
		this.bankCardId = bankCardId;
		this.sortIndex = sortIndex;
		this.status = status;
		this.addDateLong = addDateLong;
		this.updateDateLong = updateDateLong;
	}

	public PayeeInfo(String payeeId, String payeeName, String bankName, String bankCardId, String picUrl, String type, int sortIndex, byte status, long addDateLong, long updateDateLong)
	{
		this.payeeId = payeeId;
		this.payeeName = payeeName;
		this.bankName = bankName;
		this.bankCardId = bankCardId;
		this.picUrl = picUrl;
		this.type = type;
		this.sortIndex = sortIndex;
		this.status = status;
		this.addDateLong = addDateLong;
		this.updateDateLong = updateDateLong;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "payee_id", unique = true, nullable = false, length = 16)
	public String getPayeeId()
	{
		return this.payeeId;
	}

	public void setPayeeId(String payeeId)
	{
		this.payeeId = payeeId;
	}

	@Column(name = "payee_name", nullable = false, length = 32)
	public String getPayeeName()
	{
		return this.payeeName;
	}

	public void setPayeeName(String payeeName)
	{
		this.payeeName = payeeName;
	}

	@Column(name = "bank_name", nullable = false, length = 32)
	public String getBankName()
	{
		return this.bankName;
	}

	public void setBankName(String bankName)
	{
		this.bankName = bankName;
	}

	@Column(name = "bank_card_id", nullable = false, length = 20)
	public String getBankCardId()
	{
		return this.bankCardId;
	}

	public void setBankCardId(String bankCardId)
	{
		this.bankCardId = bankCardId;
	}

	@Column(name = "pic_url", length = 128)
	public String getPicUrl()
	{
		return this.picUrl;
	}

	public void setPicUrl(String picUrl)
	{
		this.picUrl = picUrl;
	}

	@Column(name = "type", length = 16)
	public String getType()
	{
		return this.type;
	}

	public void setType(String type)
	{
		this.type = type;
	}

	@Column(name = "sort_index", nullable = false)
	public int getSortIndex()
	{
		return this.sortIndex;
	}

	public void setSortIndex(int sortIndex)
	{
		this.sortIndex = sortIndex;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus()
	{
		return this.status;
	}

	public void setStatus(byte status)
	{
		this.status = status;
	}

	@Column(name = "add_date_long", nullable = false)
	public long getAddDateLong()
	{
		return this.addDateLong;
	}

	public void setAddDateLong(long addDateLong)
	{
		this.addDateLong = addDateLong;
	}

	@Column(name = "update_date_long", nullable = false)
	public long getUpdateDateLong()
	{
		return this.updateDateLong;
	}

	public void setUpdateDateLong(long updateDateLong)
	{
		this.updateDateLong = updateDateLong;
	}
}
