package com.bet.orms;
// Generated 2018-3-29 21:47:22 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * PicInfo generated by hbm2java
 */
@Entity
@Table(name = "pic_info", uniqueConstraints = @UniqueConstraint(columnNames = "pic_id"))
@Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
public class PicInfo implements java.io.Serializable
{
	private static final long serialVersionUID = 2522908634212103896L;
	private Integer id;
	private String picId;
	private String sortId;
	private String picUrl;
	private int width;
	private int height;
	private String picSizeInfo;
	private byte status;

	public PicInfo()
	{
	}

	public PicInfo(String picId, String sortId, String picUrl, int width, int height, byte status)
	{
		this.picId = picId;
		this.sortId = sortId;
		this.picUrl = picUrl;
		this.width = width;
		this.height = height;
		this.status = status;
	}

	public PicInfo(String picId, String sortId, String picUrl, int width, int height, String picSizeInfo, byte status)
	{
		this.picId = picId;
		this.sortId = sortId;
		this.picUrl = picUrl;
		this.width = width;
		this.height = height;
		this.picSizeInfo = picSizeInfo;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "pic_id", unique = true, nullable = false, length = 16)
	public String getPicId()
	{
		return this.picId;
	}

	public void setPicId(String picId)
	{
		this.picId = picId;
	}

	@Column(name = "sort_id", nullable = false, length = 16)
	public String getSortId()
	{
		return this.sortId;
	}

	public void setSortId(String sortId)
	{
		this.sortId = sortId;
	}

	@Column(name = "pic_url", nullable = false, length = 256)
	public String getPicUrl()
	{
		return this.picUrl;
	}

	public void setPicUrl(String picUrl)
	{
		this.picUrl = picUrl;
	}

	@Column(name = "width", nullable = false)
	public int getWidth()
	{
		return this.width;
	}

	public void setWidth(int width)
	{
		this.width = width;
	}

	@Column(name = "height", nullable = false)
	public int getHeight()
	{
		return this.height;
	}

	public void setHeight(int height)
	{
		this.height = height;
	}

	@Column(name = "pic_size_info", length = 512)
	public String getPicSizeInfo()
	{
		return this.picSizeInfo;
	}

	public void setPicSizeInfo(String picSizeInfo)
	{
		this.picSizeInfo = picSizeInfo;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus()
	{
		return this.status;
	}

	public void setStatus(byte status)
	{
		this.status = status;
	}
}
