package com.bet.orms;
// Generated 2018-3-29 22:07:55 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * SmsCodeInfo generated by hbm2java
 */
@Entity
@Table(name = "sms_code_info")
@Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
public class SmsCodeInfo implements java.io.Serializable
{
	private static final long serialVersionUID = -1438264728851691344L;
	private Integer id;
	private String number;
	private String verifyType;
	private String code;
	private Long startDateLong;
	private int validateTimeLong;
	private byte status;
	private long addDateLong;

	public SmsCodeInfo()
	{
	}

	public SmsCodeInfo(String number, String verifyType, String code, int validateTimeLong, byte status, long addDateLong)
	{
		this.number = number;
		this.verifyType = verifyType;
		this.code = code;
		this.validateTimeLong = validateTimeLong;
		this.status = status;
		this.addDateLong = addDateLong;
	}

	public SmsCodeInfo(String number, String verifyType, String code, Long startDateLong, int validateTimeLong, byte status, long addDateLong)
	{
		this.number = number;
		this.verifyType = verifyType;
		this.code = code;
		this.startDateLong = startDateLong;
		this.validateTimeLong = validateTimeLong;
		this.status = status;
		this.addDateLong = addDateLong;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "number", nullable = false, length = 16)
	public String getNumber()
	{
		return this.number;
	}

	public void setNumber(String number)
	{
		this.number = number;
	}

	@Column(name = "verify_type", nullable = false, length = 16)
	public String getVerifyType()
	{
		return this.verifyType;
	}

	public void setVerifyType(String verifyType)
	{
		this.verifyType = verifyType;
	}

	@Column(name = "code", nullable = false, length = 8)
	public String getCode()
	{
		return this.code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	@Column(name = "start_date_long")
	public Long getStartDateLong()
	{
		return this.startDateLong;
	}

	public void setStartDateLong(Long startDateLong)
	{
		this.startDateLong = startDateLong;
	}

	@Column(name = "validate_time_long", nullable = false)
	public int getValidateTimeLong()
	{
		return this.validateTimeLong;
	}

	public void setValidateTimeLong(int validateTimeLong)
	{
		this.validateTimeLong = validateTimeLong;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus()
	{
		return this.status;
	}

	public void setStatus(byte status)
	{
		this.status = status;
	}

	@Column(name = "add_date_long", nullable = false)
	public long getAddDateLong()
	{
		return this.addDateLong;
	}

	public void setAddDateLong(long addDateLong)
	{
		this.addDateLong = addDateLong;
	}
}
