package com.bet.orms;
// Generated 2018-3-29 21:47:22 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * SmsCodeVerifyInfo generated by hbm2java
 */
@Entity
@Table(name = "sms_code_verify_info")
@Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
public class SmsCodeVerifyInfo implements java.io.Serializable
{
	private static final long serialVersionUID = -5236834493996340773L;
	private Integer id;
	private String number;
	private String verifyType;
	private String ip;
	private String code;
	private long verifyDateLong;
	private byte status;

	public SmsCodeVerifyInfo()
	{
	}

	public SmsCodeVerifyInfo(String number, String verifyType, String ip, String code, long verifyDateLong, byte status)
	{
		this.number = number;
		this.verifyType = verifyType;
		this.ip = ip;
		this.code = code;
		this.verifyDateLong = verifyDateLong;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "number", nullable = false, length = 16)
	public String getNumber()
	{
		return this.number;
	}

	public void setNumber(String number)
	{
		this.number = number;
	}

	@Column(name = "verify_type", nullable = false, length = 16)
	public String getVerifyType()
	{
		return this.verifyType;
	}

	public void setVerifyType(String verifyType)
	{
		this.verifyType = verifyType;
	}

	@Column(name = "ip", nullable = false, length = 16)
	public String getIp()
	{
		return this.ip;
	}

	public void setIp(String ip)
	{
		this.ip = ip;
	}

	@Column(name = "code", nullable = false, length = 8)
	public String getCode()
	{
		return this.code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	@Column(name = "verify_date_long", nullable = false)
	public long getVerifyDateLong()
	{
		return this.verifyDateLong;
	}

	public void setVerifyDateLong(long verifyDateLong)
	{
		this.verifyDateLong = verifyDateLong;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus()
	{
		return this.status;
	}

	public void setStatus(byte status)
	{
		this.status = status;
	}
}
