package com.bet.orms;
// Generated 2018-3-29 21:47:22 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * SmsCodeConfigInfo generated by hbm2java
 */
@Entity
@Table(name = "sms_code_config_info", uniqueConstraints = @UniqueConstraint(columnNames = "config_id"))
@Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
public class SmsCodeConfigInfo implements java.io.Serializable
{
	private static final long serialVersionUID = 110281768965905814L;
	private Integer id;
	private String configId;
	private String name;
	private String platform;
	private String url;
	private String topic;
	private String appKey;
	private String appSecret;
	private String smsType;
	private String signName;
	private String smsParams;
	private String smsTemplateCode;
	private String mnsEndpoint;
	private int sortIndex;
	private int validateSeconds;
	private byte status;
	private String remark;
	private long addDateLong;
	private long updateDateLong;

	public SmsCodeConfigInfo()
	{
	}

	public SmsCodeConfigInfo(String configId, String name, String platform, String topic, String appKey, String appSecret, int sortIndex, int validateSeconds, byte status, long addDateLong,
		long updateDateLong)
	{
		this.configId = configId;
		this.name = name;
		this.platform = platform;
		this.topic = topic;
		this.appKey = appKey;
		this.appSecret = appSecret;
		this.sortIndex = sortIndex;
		this.validateSeconds = validateSeconds;
		this.status = status;
		this.addDateLong = addDateLong;
		this.updateDateLong = updateDateLong;
	}

	public SmsCodeConfigInfo(String configId, String name, String platform, String url, String topic, String appKey, String appSecret, String smsType, String signName, String smsParams,
		String smsTemplateCode, String mnsEndpoint, int sortIndex, int validateSeconds, byte status, String remark, long addDateLong, long updateDateLong)
	{
		this.configId = configId;
		this.name = name;
		this.platform = platform;
		this.url = url;
		this.topic = topic;
		this.appKey = appKey;
		this.appSecret = appSecret;
		this.smsType = smsType;
		this.signName = signName;
		this.smsParams = smsParams;
		this.smsTemplateCode = smsTemplateCode;
		this.mnsEndpoint = mnsEndpoint;
		this.sortIndex = sortIndex;
		this.validateSeconds = validateSeconds;
		this.status = status;
		this.remark = remark;
		this.addDateLong = addDateLong;
		this.updateDateLong = updateDateLong;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "config_id", unique = true, nullable = false, length = 16)
	public String getConfigId()
	{
		return this.configId;
	}

	public void setConfigId(String configId)
	{
		this.configId = configId;
	}

	@Column(name = "name", nullable = false, length = 32)
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	@Column(name = "platform", nullable = false, length = 32)
	public String getPlatform()
	{
		return this.platform;
	}

	public void setPlatform(String platform)
	{
		this.platform = platform;
	}

	@Column(name = "url", length = 128)
	public String getUrl()
	{
		return this.url;
	}

	public void setUrl(String url)
	{
		this.url = url;
	}

	@Column(name = "topic", nullable = false, length = 256)
	public String getTopic()
	{
		return this.topic;
	}

	public void setTopic(String topic)
	{
		this.topic = topic;
	}

	@Column(name = "app_key", nullable = false, length = 32)
	public String getAppKey()
	{
		return this.appKey;
	}

	public void setAppKey(String appKey)
	{
		this.appKey = appKey;
	}

	@Column(name = "app_secret", nullable = false, length = 64)
	public String getAppSecret()
	{
		return this.appSecret;
	}

	public void setAppSecret(String appSecret)
	{
		this.appSecret = appSecret;
	}

	@Column(name = "sms_type", length = 32)
	public String getSmsType()
	{
		return this.smsType;
	}

	public void setSmsType(String smsType)
	{
		this.smsType = smsType;
	}

	@Column(name = "sign_name", length = 256)
	public String getSignName()
	{
		return this.signName;
	}

	public void setSignName(String signName)
	{
		this.signName = signName;
	}

	@Column(name = "sms_params", length = 256)
	public String getSmsParams()
	{
		return this.smsParams;
	}

	public void setSmsParams(String smsParams)
	{
		this.smsParams = smsParams;
	}

	@Column(name = "sms_template_code", length = 256)
	public String getSmsTemplateCode()
	{
		return this.smsTemplateCode;
	}

	public void setSmsTemplateCode(String smsTemplateCode)
	{
		this.smsTemplateCode = smsTemplateCode;
	}

	@Column(name = "mns_endpoint", length = 512)
	public String getMnsEndpoint()
	{
		return this.mnsEndpoint;
	}

	public void setMnsEndpoint(String mnsEndpoint)
	{
		this.mnsEndpoint = mnsEndpoint;
	}

	@Column(name = "sort_index", nullable = false)
	public int getSortIndex()
	{
		return this.sortIndex;
	}

	public void setSortIndex(int sortIndex)
	{
		this.sortIndex = sortIndex;
	}

	@Column(name = "validate_seconds", nullable = false)
	public int getValidateSeconds()
	{
		return this.validateSeconds;
	}

	public void setValidateSeconds(int validateSeconds)
	{
		this.validateSeconds = validateSeconds;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus()
	{
		return this.status;
	}

	public void setStatus(byte status)
	{
		this.status = status;
	}

	@Column(name = "remark", length = 65535)
	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	@Column(name = "add_date_long", nullable = false)
	public long getAddDateLong()
	{
		return this.addDateLong;
	}

	public void setAddDateLong(long addDateLong)
	{
		this.addDateLong = addDateLong;
	}

	@Column(name = "update_date_long", nullable = false)
	public long getUpdateDateLong()
	{
		return this.updateDateLong;
	}

	public void setUpdateDateLong(long updateDateLong)
	{
		this.updateDateLong = updateDateLong;
	}
}
