package com.bet.orms;
// Generated 2018-4-2 11:48:48 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * TeamInfo generated by hbm2java
 */
@Entity
@Table(name = "team_info", uniqueConstraints = @UniqueConstraint(columnNames = "team_id"))
@Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
public class TeamInfo implements java.io.Serializable
{
	private static final long serialVersionUID = 7832191252166461225L;
	private Integer id;
	private String teamId;
	private String name;
	private String picUrl;
	private byte status;
	private long addDateLong;
	private long updateDateLong;

	public TeamInfo()
	{
	}

	public TeamInfo(String teamId, String name, byte status, long addDateLong, long updateDateLong)
	{
		this.teamId = teamId;
		this.name = name;
		this.status = status;
		this.addDateLong = addDateLong;
		this.updateDateLong = updateDateLong;
	}

	public TeamInfo(String teamId, String name, String picUrl, byte status, long addDateLong, long updateDateLong)
	{
		this.teamId = teamId;
		this.name = name;
		this.picUrl = picUrl;
		this.status = status;
		this.addDateLong = addDateLong;
		this.updateDateLong = updateDateLong;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "team_id", unique = true, nullable = false, length = 16)
	public String getTeamId()
	{
		return this.teamId;
	}

	public void setTeamId(String teamId)
	{
		this.teamId = teamId;
	}

	@Column(name = "name", nullable = false, length = 64)
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	@Column(name = "pic_url", length = 128)
	public String getPicUrl()
	{
		return this.picUrl;
	}

	public void setPicUrl(String picUrl)
	{
		this.picUrl = picUrl;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus()
	{
		return this.status;
	}

	public void setStatus(byte status)
	{
		this.status = status;
	}

	@Column(name = "add_date_long", nullable = false)
	public long getAddDateLong()
	{
		return this.addDateLong;
	}

	public void setAddDateLong(long addDateLong)
	{
		this.addDateLong = addDateLong;
	}

	@Column(name = "update_date_long", nullable = false)
	public long getUpdateDateLong()
	{
		return this.updateDateLong;
	}

	public void setUpdateDateLong(long updateDateLong)
	{
		this.updateDateLong = updateDateLong;
	}
}
