package com.bet.orms;
// Generated 2018-4-18 10:21:07 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * TeamProfitRateInfo generated by hbm2java
 */
@Entity
@Table(name = "team_profit_rate_info", uniqueConstraints = @UniqueConstraint(columnNames = "rate_id"))
@Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
public class TeamProfitRateInfo implements java.io.Serializable
{
	private static final long serialVersionUID = 8220127222849112786L;
	private Integer id;
	private String rateId;
	private String name;
	private int type1;
	private int type2;
	private int type3;
	private int type4;
	private int type5;
	private int type6;
	private int type7;
	private int sameLevel;
	private byte status;
	private long addDateLong;
	private long updateDateLong;

	public TeamProfitRateInfo()
	{
	}

	public TeamProfitRateInfo(String rateId, String name, int type1, int type2, int type3, int type4, int type5, int type6, int type7, int sameLevel, byte status, long addDateLong,
		long updateDateLong)
	{
		this.rateId = rateId;
		this.name = name;
		this.type1 = type1;
		this.type2 = type2;
		this.type3 = type3;
		this.type4 = type4;
		this.type5 = type5;
		this.type6 = type6;
		this.type7 = type7;
		this.sameLevel = sameLevel;
		this.status = status;
		this.addDateLong = addDateLong;
		this.updateDateLong = updateDateLong;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "rate_id", unique = true, nullable = false, length = 16)
	public String getRateId()
	{
		return this.rateId;
	}

	public void setRateId(String rateId)
	{
		this.rateId = rateId;
	}

	@Column(name = "name", nullable = false, length = 16)
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	@Column(name = "type1", nullable = false)
	public int getType1()
	{
		return this.type1;
	}

	public void setType1(int type1)
	{
		this.type1 = type1;
	}

	@Column(name = "type2", nullable = false)
	public int getType2()
	{
		return this.type2;
	}

	public void setType2(int type2)
	{
		this.type2 = type2;
	}

	@Column(name = "type3", nullable = false)
	public int getType3()
	{
		return this.type3;
	}

	public void setType3(int type3)
	{
		this.type3 = type3;
	}

	@Column(name = "type4", nullable = false)
	public int getType4()
	{
		return this.type4;
	}

	public void setType4(int type4)
	{
		this.type4 = type4;
	}

	@Column(name = "type5", nullable = false)
	public int getType5()
	{
		return this.type5;
	}

	public void setType5(int type5)
	{
		this.type5 = type5;
	}

	@Column(name = "type6", nullable = false)
	public int getType6()
	{
		return this.type6;
	}

	public void setType6(int type6)
	{
		this.type6 = type6;
	}

	@Column(name = "type7", nullable = false)
	public int getType7()
	{
		return this.type7;
	}

	public void setType7(int type7)
	{
		this.type7 = type7;
	}

	@Column(name = "same_level", nullable = false)
	public int getSameLevel()
	{
		return this.sameLevel;
	}

	public void setSameLevel(int sameLevel)
	{
		this.sameLevel = sameLevel;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus()
	{
		return this.status;
	}

	public void setStatus(byte status)
	{
		this.status = status;
	}

	@Column(name = "add_date_long", nullable = false)
	public long getAddDateLong()
	{
		return this.addDateLong;
	}

	public void setAddDateLong(long addDateLong)
	{
		this.addDateLong = addDateLong;
	}

	@Column(name = "update_date_long", nullable = false)
	public long getUpdateDateLong()
	{
		return this.updateDateLong;
	}

	public void setUpdateDateLong(long updateDateLong)
	{
		this.updateDateLong = updateDateLong;
	}
}
