package com.bet.orms;
// Generated 2018-4-22 11:53:02 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * TeamLeaderProfitConfigInfo generated by hbm2java
 */
@Entity
@Table(name = "team_leader_profit_config_info", uniqueConstraints = @UniqueConstraint(columnNames = "config_id"))
@Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
public class TeamLeaderProfitConfigInfo implements java.io.Serializable
{
	private static final long serialVersionUID = -7679287387564209748L;
	private Integer id;
	private String configId;
	private String name;
	private byte userType;
	private long teamBetMoney;
	private long userBetMoney;
	private int profitPercent;
	private long profitMaxMoney;
	private int fee;
	private byte status;
	private long addDateLong;
	private long updateDateLong;

	public TeamLeaderProfitConfigInfo()
	{
	}

	public TeamLeaderProfitConfigInfo(String configId, String name, byte userType, long teamBetMoney, long userBetMoney, int profitPercent, long profitMaxMoney, int fee, byte status, long addDateLong,
		long updateDateLong)
	{
		this.configId = configId;
		this.name = name;
		this.userType = userType;
		this.teamBetMoney = teamBetMoney;
		this.userBetMoney = userBetMoney;
		this.profitPercent = profitPercent;
		this.profitMaxMoney = profitMaxMoney;
		this.fee = fee;
		this.status = status;
		this.addDateLong = addDateLong;
		this.updateDateLong = updateDateLong;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "config_id", unique = true, nullable = false, length = 16)
	public String getConfigId()
	{
		return this.configId;
	}

	public void setConfigId(String configId)
	{
		this.configId = configId;
	}

	@Column(name = "name", nullable = false, length = 16)
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	@Column(name = "user_type", nullable = false)
	public byte getUserType()
	{
		return this.userType;
	}

	public void setUserType(byte userType)
	{
		this.userType = userType;
	}

	@Column(name = "team_bet_money", nullable = false)
	public long getTeamBetMoney()
	{
		return this.teamBetMoney;
	}

	public void setTeamBetMoney(long teamBetMoney)
	{
		this.teamBetMoney = teamBetMoney;
	}

	@Column(name = "user_bet_money", nullable = false)
	public long getUserBetMoney()
	{
		return this.userBetMoney;
	}

	public void setUserBetMoney(long userBetMoney)
	{
		this.userBetMoney = userBetMoney;
	}

	@Column(name = "profit_percent", nullable = false)
	public int getProfitPercent()
	{
		return this.profitPercent;
	}

	public void setProfitPercent(int profitPercent)
	{
		this.profitPercent = profitPercent;
	}

	@Column(name = "profit_max_money", nullable = false)
	public long getProfitMaxMoney()
	{
		return this.profitMaxMoney;
	}

	public void setProfitMaxMoney(long profitMaxMoney)
	{
		this.profitMaxMoney = profitMaxMoney;
	}

	@Column(name = "fee", nullable = false)
	public int getFee()
	{
		return this.fee;
	}

	public void setFee(int fee)
	{
		this.fee = fee;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus()
	{
		return this.status;
	}

	public void setStatus(byte status)
	{
		this.status = status;
	}

	@Column(name = "add_date_long", nullable = false)
	public long getAddDateLong()
	{
		return this.addDateLong;
	}

	public void setAddDateLong(long addDateLong)
	{
		this.addDateLong = addDateLong;
	}

	@Column(name = "update_date_long", nullable = false)
	public long getUpdateDateLong()
	{
		return this.updateDateLong;
	}

	public void setUpdateDateLong(long updateDateLong)
	{
		this.updateDateLong = updateDateLong;
	}
}
