package com.bet.orms;
// Generated 2018-5-2 23:26:11 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * TeamProfitInfo generated by hbm2java
 */
@Entity
@Table(name = "team_profit_info", uniqueConstraints = @UniqueConstraint(columnNames = "profit_id"))
@Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
public class TeamProfitInfo implements java.io.Serializable
{
	private static final long serialVersionUID = -3517665189553747247L;
	private Integer id;
	private String profitId;
	private String betId;
	private String betUserId;
	private String phaseId;
	private String userId;
	private long winMoney;
	private byte profitType;
	private long profitMoney;
	private long profitUserMoney;
	private long fee;
	private byte profitStatus;
	private byte sysStatus;
	private byte status;
	private long addDateLong;
	private long updateDateLong;

	public TeamProfitInfo()
	{
	}

	public TeamProfitInfo(String profitId, String betId, String betUserId, String phaseId, String userId, long winMoney, byte profitType, long profitMoney, long profitUserMoney, long fee,
		byte profitStatus, byte sysStatus, byte status, long addDateLong, long updateDateLong)
	{
		this.profitId = profitId;
		this.betId = betId;
		this.betUserId = betUserId;
		this.phaseId = phaseId;
		this.userId = userId;
		this.winMoney = winMoney;
		this.profitType = profitType;
		this.profitMoney = profitMoney;
		this.profitUserMoney = profitUserMoney;
		this.fee = fee;
		this.profitStatus = profitStatus;
		this.sysStatus = sysStatus;
		this.status = status;
		this.addDateLong = addDateLong;
		this.updateDateLong = updateDateLong;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "profit_id", unique = true, nullable = false, length = 16)
	public String getProfitId()
	{
		return this.profitId;
	}

	public void setProfitId(String profitId)
	{
		this.profitId = profitId;
	}

	@Column(name = "bet_id", nullable = false, length = 16)
	public String getBetId()
	{
		return this.betId;
	}

	public void setBetId(String betId)
	{
		this.betId = betId;
	}

	@Column(name = "bet_user_id", nullable = false, length = 16)
	public String getBetUserId()
	{
		return this.betUserId;
	}

	public void setBetUserId(String betUserId)
	{
		this.betUserId = betUserId;
	}

	@Column(name = "phase_id", nullable = false, length = 16)
	public String getPhaseId()
	{
		return this.phaseId;
	}

	public void setPhaseId(String phaseId)
	{
		this.phaseId = phaseId;
	}

	@Column(name = "user_id", nullable = false, length = 16)
	public String getUserId()
	{
		return this.userId;
	}

	public void setUserId(String userId)
	{
		this.userId = userId;
	}

	@Column(name = "win_money", nullable = false)
	public long getWinMoney()
	{
		return this.winMoney;
	}

	public void setWinMoney(long winMoney)
	{
		this.winMoney = winMoney;
	}

	@Column(name = "profit_type", nullable = false)
	public byte getProfitType()
	{
		return this.profitType;
	}

	public void setProfitType(byte profitType)
	{
		this.profitType = profitType;
	}

	@Column(name = "profit_money", nullable = false)
	public long getProfitMoney()
	{
		return this.profitMoney;
	}

	public void setProfitMoney(long profitMoney)
	{
		this.profitMoney = profitMoney;
	}

	@Column(name = "profit_user_money", nullable = false)
	public long getProfitUserMoney()
	{
		return this.profitUserMoney;
	}

	public void setProfitUserMoney(long profitUserMoney)
	{
		this.profitUserMoney = profitUserMoney;
	}

	@Column(name = "fee", nullable = false)
	public long getFee()
	{
		return this.fee;
	}

	public void setFee(long fee)
	{
		this.fee = fee;
	}

	@Column(name = "profit_status", nullable = false)
	public byte getProfitStatus()
	{
		return this.profitStatus;
	}

	public void setProfitStatus(byte profitStatus)
	{
		this.profitStatus = profitStatus;
	}

	@Column(name = "sys_status", nullable = false)
	public byte getSysStatus()
	{
		return this.sysStatus;
	}

	public void setSysStatus(byte sysStatus)
	{
		this.sysStatus = sysStatus;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus()
	{
		return this.status;
	}

	public void setStatus(byte status)
	{
		this.status = status;
	}

	@Column(name = "add_date_long", nullable = false)
	public long getAddDateLong()
	{
		return this.addDateLong;
	}

	public void setAddDateLong(long addDateLong)
	{
		this.addDateLong = addDateLong;
	}

	@Column(name = "update_date_long", nullable = false)
	public long getUpdateDateLong()
	{
		return this.updateDateLong;
	}

	public void setUpdateDateLong(long updateDateLong)
	{
		this.updateDateLong = updateDateLong;
	}
}
