package com.bet.orms;
// Generated 2018-4-22 12:11:04 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * UserBalanceLogInfo generated by hbm2java
 */
@Entity
@Table(name = "user_balance_log_info")
@Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
public class UserBalanceLogInfo implements java.io.Serializable
{
	private static final long serialVersionUID = 5915141015128819591L;
	private Integer id;
	private String userId;
	private long money;
	private byte moneyUnit;
	private String logType;
	private String serverId;
	private String reserveId1;
	private String reserveId2;
	private String reserveId3;
	private String remark;
	private long addDateLong;

	public UserBalanceLogInfo()
	{
	}

	public UserBalanceLogInfo(String userId, long money, byte moneyUnit, long addDateLong)
	{
		this.userId = userId;
		this.money = money;
		this.moneyUnit = moneyUnit;
		this.addDateLong = addDateLong;
	}

	public UserBalanceLogInfo(String userId, long money, byte moneyUnit, String logType, String serverId, String reserveId1, String reserveId2, String reserveId3, String remark, long addDateLong)
	{
		this.userId = userId;
		this.money = money;
		this.moneyUnit = moneyUnit;
		this.logType = logType;
		this.serverId = serverId;
		this.reserveId1 = reserveId1;
		this.reserveId2 = reserveId2;
		this.reserveId3 = reserveId3;
		this.remark = remark;
		this.addDateLong = addDateLong;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "user_id", nullable = false, length = 32)
	public String getUserId()
	{
		return this.userId;
	}

	public void setUserId(String userId)
	{
		this.userId = userId;
	}

	@Column(name = "money", nullable = false)
	public long getMoney()
	{
		return this.money;
	}

	public void setMoney(long money)
	{
		this.money = money;
	}

	@Column(name = "money_unit", nullable = false)
	public byte getMoneyUnit()
	{
		return this.moneyUnit;
	}

	public void setMoneyUnit(byte moneyUnit)
	{
		this.moneyUnit = moneyUnit;
	}

	@Column(name = "log_type", length = 32)
	public String getLogType()
	{
		return this.logType;
	}

	public void setLogType(String logType)
	{
		this.logType = logType;
	}

	@Column(name = "server_id", length = 32)
	public String getServerId()
	{
		return this.serverId;
	}

	public void setServerId(String serverId)
	{
		this.serverId = serverId;
	}

	@Column(name = "reserve_id1", length = 32)
	public String getReserveId1()
	{
		return this.reserveId1;
	}

	public void setReserveId1(String reserveId1)
	{
		this.reserveId1 = reserveId1;
	}

	@Column(name = "reserve_id2", length = 32)
	public String getReserveId2()
	{
		return this.reserveId2;
	}

	public void setReserveId2(String reserveId2)
	{
		this.reserveId2 = reserveId2;
	}

	@Column(name = "reserve_id3", length = 32)
	public String getReserveId3()
	{
		return this.reserveId3;
	}

	public void setReserveId3(String reserveId3)
	{
		this.reserveId3 = reserveId3;
	}

	@Column(name = "remark", length = 256)
	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	@Column(name = "add_date_long", nullable = false)
	public long getAddDateLong()
	{
		return this.addDateLong;
	}

	public void setAddDateLong(long addDateLong)
	{
		this.addDateLong = addDateLong;
	}
}
