package com.bet.orms;
// Generated 2018-3-29 21:47:22 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * UserTypeChangeLogInfo generated by hbm2java
 */
@Entity
@Table(name = "user_type_change_log_info")
@Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
public class UserTypeChangeLogInfo implements java.io.Serializable
{
	private static final long serialVersionUID = -1875341695300537530L;
	private Integer id;
	private String userId;
	private String adminId;
	private byte userType;
	private long addDateLong;

	public UserTypeChangeLogInfo()
	{
	}

	public UserTypeChangeLogInfo(String userId, byte userType, long addDateLong)
	{
		this.userId = userId;
		this.userType = userType;
		this.addDateLong = addDateLong;
	}

	public UserTypeChangeLogInfo(String userId, String adminId, byte userType, long addDateLong)
	{
		this.userId = userId;
		this.adminId = adminId;
		this.userType = userType;
		this.addDateLong = addDateLong;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "user_id", nullable = false, length = 16)
	public String getUserId()
	{
		return this.userId;
	}

	public void setUserId(String userId)
	{
		this.userId = userId;
	}

	@Column(name = "admin_id", length = 16)
	public String getAdminId()
	{
		return this.adminId;
	}

	public void setAdminId(String adminId)
	{
		this.adminId = adminId;
	}

	@Column(name = "user_type", nullable = false)
	public byte getUserType()
	{
		return this.userType;
	}

	public void setUserType(byte userType)
	{
		this.userType = userType;
	}

	@Column(name = "add_date_long", nullable = false)
	public long getAddDateLong()
	{
		return this.addDateLong;
	}

	public void setAddDateLong(long addDateLong)
	{
		this.addDateLong = addDateLong;
	}
}
