package com.bet.orms;
// Generated 2018-5-5 10:42:45 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * UserInfo generated by hbm2java
 */
@Entity
@Table(name = "user_info", uniqueConstraints = { @UniqueConstraint(columnNames = "number"), @UniqueConstraint(columnNames = "user_id") })
@Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
public class UserInfo implements java.io.Serializable
{
	private static final long serialVersionUID = -7307090887198004986L;
	private Integer id;
	private String userId;
	private String password;
	private String password2;
	private String sessionId;
	private byte userType;
	private String parentId;
	private String parentSign;
	private String referrerId;
	private Long referrerDateLong;
	private String parentsId;
	private String number;
	private String name;
	private String nickname;
	private Byte sex;
	private String picUrl;
	private String birthday;
	private String country;
	private String province;
	private String city;
	private String address;
	private String identityCard;
	private String payeeName;
	private String bankName;
	private String bankCardId;
	private String qrUrl;
	private long point;
	private long freezePoint;
	private long rewardPoint;
	private long givePoint;
	private Long giveValidateDateLong;
	private byte numberVerifyStatus;
	private byte authStatus;
	private byte activeStatus;
	private byte sysStatus;
	private byte status;
	private String remark;
	private long regDateLong;
	private Long activeDateLong;

	public UserInfo()
	{
	}

	public UserInfo(String userId, String password, String password2, byte userType, long point, long freezePoint, long rewardPoint, long givePoint, byte numberVerifyStatus, byte authStatus,
		byte activeStatus, byte sysStatus, byte status, long regDateLong)
	{
		this.userId = userId;
		this.password = password;
		this.password2 = password2;
		this.userType = userType;
		this.point = point;
		this.freezePoint = freezePoint;
		this.rewardPoint = rewardPoint;
		this.givePoint = givePoint;
		this.numberVerifyStatus = numberVerifyStatus;
		this.authStatus = authStatus;
		this.activeStatus = activeStatus;
		this.sysStatus = sysStatus;
		this.status = status;
		this.regDateLong = regDateLong;
	}

	public UserInfo(String userId, String password, String password2, String sessionId, byte userType, String parentId, String parentSign, String referrerId, Long referrerDateLong, String parentsId,
		String number, String name, String nickname, Byte sex, String picUrl, String birthday, String country, String province, String city, String address, String identityCard, String payeeName,
		String bankName, String bankCardId, String qrUrl, long point, long freezePoint, long rewardPoint, long givePoint, Long giveValidateDateLong, byte numberVerifyStatus, byte authStatus,
		byte activeStatus, byte sysStatus, byte status, String remark, long regDateLong, Long activeDateLong)
	{
		this.userId = userId;
		this.password = password;
		this.password2 = password2;
		this.sessionId = sessionId;
		this.userType = userType;
		this.parentId = parentId;
		this.parentSign = parentSign;
		this.referrerId = referrerId;
		this.referrerDateLong = referrerDateLong;
		this.parentsId = parentsId;
		this.number = number;
		this.name = name;
		this.nickname = nickname;
		this.sex = sex;
		this.picUrl = picUrl;
		this.birthday = birthday;
		this.country = country;
		this.province = province;
		this.city = city;
		this.address = address;
		this.identityCard = identityCard;
		this.payeeName = payeeName;
		this.bankName = bankName;
		this.bankCardId = bankCardId;
		this.qrUrl = qrUrl;
		this.point = point;
		this.freezePoint = freezePoint;
		this.rewardPoint = rewardPoint;
		this.givePoint = givePoint;
		this.giveValidateDateLong = giveValidateDateLong;
		this.numberVerifyStatus = numberVerifyStatus;
		this.authStatus = authStatus;
		this.activeStatus = activeStatus;
		this.sysStatus = sysStatus;
		this.status = status;
		this.remark = remark;
		this.regDateLong = regDateLong;
		this.activeDateLong = activeDateLong;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "user_id", unique = true, nullable = false, length = 16)
	public String getUserId()
	{
		return this.userId;
	}

	public void setUserId(String userId)
	{
		this.userId = userId;
	}

	@Column(name = "password", nullable = false, length = 32)
	public String getPassword()
	{
		return this.password;
	}

	public void setPassword(String password)
	{
		this.password = password;
	}

	@Column(name = "password2", nullable = false, length = 32)
	public String getPassword2()
	{
		return this.password2;
	}

	public void setPassword2(String password2)
	{
		this.password2 = password2;
	}

	@Column(name = "session_id", length = 128)
	public String getSessionId()
	{
		return this.sessionId;
	}

	public void setSessionId(String sessionId)
	{
		this.sessionId = sessionId;
	}

	@Column(name = "user_type", nullable = false)
	public byte getUserType()
	{
		return this.userType;
	}

	public void setUserType(byte userType)
	{
		this.userType = userType;
	}

	@Column(name = "parent_id", length = 16)
	public String getParentId()
	{
		return this.parentId;
	}

	public void setParentId(String parentId)
	{
		this.parentId = parentId;
	}

	@Column(name = "parent_sign", length = 16)
	public String getParentSign()
	{
		return this.parentSign;
	}

	public void setParentSign(String parentSign)
	{
		this.parentSign = parentSign;
	}

	@Column(name = "referrer_id", length = 16)
	public String getReferrerId()
	{
		return this.referrerId;
	}

	public void setReferrerId(String referrerId)
	{
		this.referrerId = referrerId;
	}

	@Column(name = "referrer_date_long")
	public Long getReferrerDateLong()
	{
		return this.referrerDateLong;
	}

	public void setReferrerDateLong(Long referrerDateLong)
	{
		this.referrerDateLong = referrerDateLong;
	}

	@Column(name = "parents_id", length = 65535)
	public String getParentsId()
	{
		return this.parentsId;
	}

	public void setParentsId(String parentsId)
	{
		this.parentsId = parentsId;
	}

	@Column(name = "number", unique = true, length = 16)
	public String getNumber()
	{
		return this.number;
	}

	public void setNumber(String number)
	{
		this.number = number;
	}

	@Column(name = "name", length = 32)
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	@Column(name = "nickname", length = 32)
	public String getNickname()
	{
		return this.nickname;
	}

	public void setNickname(String nickname)
	{
		this.nickname = nickname;
	}

	@Column(name = "sex")
	public Byte getSex()
	{
		return this.sex;
	}

	public void setSex(Byte sex)
	{
		this.sex = sex;
	}

	@Column(name = "pic_url", length = 128)
	public String getPicUrl()
	{
		return this.picUrl;
	}

	public void setPicUrl(String picUrl)
	{
		this.picUrl = picUrl;
	}

	@Column(name = "birthday", length = 20)
	public String getBirthday()
	{
		return this.birthday;
	}

	public void setBirthday(String birthday)
	{
		this.birthday = birthday;
	}

	@Column(name = "country", length = 32)
	public String getCountry()
	{
		return this.country;
	}

	public void setCountry(String country)
	{
		this.country = country;
	}

	@Column(name = "province", length = 32)
	public String getProvince()
	{
		return this.province;
	}

	public void setProvince(String province)
	{
		this.province = province;
	}

	@Column(name = "city", length = 32)
	public String getCity()
	{
		return this.city;
	}

	public void setCity(String city)
	{
		this.city = city;
	}

	@Column(name = "address", length = 128)
	public String getAddress()
	{
		return this.address;
	}

	public void setAddress(String address)
	{
		this.address = address;
	}

	@Column(name = "identity_card", length = 20)
	public String getIdentityCard()
	{
		return this.identityCard;
	}

	public void setIdentityCard(String identityCard)
	{
		this.identityCard = identityCard;
	}

	@Column(name = "payee_name", length = 32)
	public String getPayeeName()
	{
		return this.payeeName;
	}

	public void setPayeeName(String payeeName)
	{
		this.payeeName = payeeName;
	}

	@Column(name = "bank_name", length = 32)
	public String getBankName()
	{
		return this.bankName;
	}

	public void setBankName(String bankName)
	{
		this.bankName = bankName;
	}

	@Column(name = "bank_card_id", length = 20)
	public String getBankCardId()
	{
		return this.bankCardId;
	}

	public void setBankCardId(String bankCardId)
	{
		this.bankCardId = bankCardId;
	}

	@Column(name = "qr_url", length = 128)
	public String getQrUrl()
	{
		return this.qrUrl;
	}

	public void setQrUrl(String qrUrl)
	{
		this.qrUrl = qrUrl;
	}

	@Column(name = "point", nullable = false)
	public long getPoint()
	{
		return this.point;
	}

	public void setPoint(long point)
	{
		this.point = point;
	}

	@Column(name = "freeze_point", nullable = false)
	public long getFreezePoint()
	{
		return this.freezePoint;
	}

	public void setFreezePoint(long freezePoint)
	{
		this.freezePoint = freezePoint;
	}

	@Column(name = "reward_point", nullable = false)
	public long getRewardPoint()
	{
		return this.rewardPoint;
	}

	public void setRewardPoint(long rewardPoint)
	{
		this.rewardPoint = rewardPoint;
	}

	@Column(name = "give_point", nullable = false)
	public long getGivePoint()
	{
		return this.givePoint;
	}

	public void setGivePoint(long givePoint)
	{
		this.givePoint = givePoint;
	}

	@Column(name = "give_validate_date_long")
	public Long getGiveValidateDateLong()
	{
		return this.giveValidateDateLong;
	}

	public void setGiveValidateDateLong(Long giveValidateDateLong)
	{
		this.giveValidateDateLong = giveValidateDateLong;
	}

	@Column(name = "number_verify_status", nullable = false)
	public byte getNumberVerifyStatus()
	{
		return this.numberVerifyStatus;
	}

	public void setNumberVerifyStatus(byte numberVerifyStatus)
	{
		this.numberVerifyStatus = numberVerifyStatus;
	}

	@Column(name = "auth_status", nullable = false)
	public byte getAuthStatus()
	{
		return this.authStatus;
	}

	public void setAuthStatus(byte authStatus)
	{
		this.authStatus = authStatus;
	}

	@Column(name = "active_status", nullable = false)
	public byte getActiveStatus()
	{
		return this.activeStatus;
	}

	public void setActiveStatus(byte activeStatus)
	{
		this.activeStatus = activeStatus;
	}

	@Column(name = "sys_status", nullable = false)
	public byte getSysStatus()
	{
		return this.sysStatus;
	}

	public void setSysStatus(byte sysStatus)
	{
		this.sysStatus = sysStatus;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus()
	{
		return this.status;
	}

	public void setStatus(byte status)
	{
		this.status = status;
	}

	@Column(name = "remark", length = 65535)
	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	@Column(name = "reg_date_long", nullable = false)
	public long getRegDateLong()
	{
		return this.regDateLong;
	}

	public void setRegDateLong(long regDateLong)
	{
		this.regDateLong = regDateLong;
	}

	@Column(name = "active_date_long")
	public Long getActiveDateLong()
	{
		return this.activeDateLong;
	}

	public void setActiveDateLong(Long activeDateLong)
	{
		this.activeDateLong = activeDateLong;
	}
}
