package com.bet.orms;
// Generated 2018-4-22 12:01:30 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * UserRechargeInfo generated by hbm2java
 */
@Entity
@Table(name = "user_recharge_info", uniqueConstraints = @UniqueConstraint(columnNames = "recharge_id"))
@Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
public class UserRechargeInfo implements java.io.Serializable
{
	private static final long serialVersionUID = 1544196301956844240L;
	private Integer id;
	private String rechargeId;
	private String userId;
	private long money;
	private byte moneyUnit;
	private long userMoney;
	private long fee;
	private String payName;
	private String payBankName;
	private String payBankCardId;
	private String payeeName;
	private String payeeBankName;
	private String payeeBankCardId;
	private String payPicUrl;
	private String payRemark;
	private byte status;
	private Long verifyDateLong;
	private Long payDateLong;
	private long addDateLong;
	private long updateDateLong;

	public UserRechargeInfo()
	{
	}

	public UserRechargeInfo(String rechargeId, String userId, long money, byte moneyUnit, long userMoney, long fee, String payName, String payBankName, String payBankCardId, String payeeName,
		String payeeBankName, String payeeBankCardId, String payPicUrl, byte status, long addDateLong, long updateDateLong)
	{
		this.rechargeId = rechargeId;
		this.userId = userId;
		this.money = money;
		this.moneyUnit = moneyUnit;
		this.userMoney = userMoney;
		this.fee = fee;
		this.payName = payName;
		this.payBankName = payBankName;
		this.payBankCardId = payBankCardId;
		this.payeeName = payeeName;
		this.payeeBankName = payeeBankName;
		this.payeeBankCardId = payeeBankCardId;
		this.payPicUrl = payPicUrl;
		this.status = status;
		this.addDateLong = addDateLong;
		this.updateDateLong = updateDateLong;
	}

	public UserRechargeInfo(String rechargeId, String userId, long money, byte moneyUnit, long userMoney, long fee, String payName, String payBankName, String payBankCardId, String payeeName,
		String payeeBankName, String payeeBankCardId, String payPicUrl, String payRemark, byte status, Long verifyDateLong, Long payDateLong, long addDateLong, long updateDateLong)
	{
		this.rechargeId = rechargeId;
		this.userId = userId;
		this.money = money;
		this.moneyUnit = moneyUnit;
		this.userMoney = userMoney;
		this.fee = fee;
		this.payName = payName;
		this.payBankName = payBankName;
		this.payBankCardId = payBankCardId;
		this.payeeName = payeeName;
		this.payeeBankName = payeeBankName;
		this.payeeBankCardId = payeeBankCardId;
		this.payPicUrl = payPicUrl;
		this.payRemark = payRemark;
		this.status = status;
		this.verifyDateLong = verifyDateLong;
		this.payDateLong = payDateLong;
		this.addDateLong = addDateLong;
		this.updateDateLong = updateDateLong;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "recharge_id", unique = true, nullable = false, length = 16)
	public String getRechargeId()
	{
		return this.rechargeId;
	}

	public void setRechargeId(String rechargeId)
	{
		this.rechargeId = rechargeId;
	}

	@Column(name = "user_id", nullable = false, length = 16)
	public String getUserId()
	{
		return this.userId;
	}

	public void setUserId(String userId)
	{
		this.userId = userId;
	}

	@Column(name = "money", nullable = false)
	public long getMoney()
	{
		return this.money;
	}

	public void setMoney(long money)
	{
		this.money = money;
	}

	@Column(name = "money_unit", nullable = false)
	public byte getMoneyUnit()
	{
		return this.moneyUnit;
	}

	public void setMoneyUnit(byte moneyUnit)
	{
		this.moneyUnit = moneyUnit;
	}

	@Column(name = "user_money", nullable = false)
	public long getUserMoney()
	{
		return this.userMoney;
	}

	public void setUserMoney(long userMoney)
	{
		this.userMoney = userMoney;
	}

	@Column(name = "fee", nullable = false)
	public long getFee()
	{
		return this.fee;
	}

	public void setFee(long fee)
	{
		this.fee = fee;
	}

	@Column(name = "pay_name", nullable = false, length = 32)
	public String getPayName()
	{
		return this.payName;
	}

	public void setPayName(String payName)
	{
		this.payName = payName;
	}

	@Column(name = "pay_bank_name", nullable = false, length = 32)
	public String getPayBankName()
	{
		return this.payBankName;
	}

	public void setPayBankName(String payBankName)
	{
		this.payBankName = payBankName;
	}

	@Column(name = "pay_bank_card_id", nullable = false, length = 20)
	public String getPayBankCardId()
	{
		return this.payBankCardId;
	}

	public void setPayBankCardId(String payBankCardId)
	{
		this.payBankCardId = payBankCardId;
	}

	@Column(name = "payee_name", nullable = false, length = 32)
	public String getPayeeName()
	{
		return this.payeeName;
	}

	public void setPayeeName(String payeeName)
	{
		this.payeeName = payeeName;
	}

	@Column(name = "payee_bank_name", nullable = false, length = 32)
	public String getPayeeBankName()
	{
		return this.payeeBankName;
	}

	public void setPayeeBankName(String payeeBankName)
	{
		this.payeeBankName = payeeBankName;
	}

	@Column(name = "payee_bank_card_id", nullable = false, length = 20)
	public String getPayeeBankCardId()
	{
		return this.payeeBankCardId;
	}

	public void setPayeeBankCardId(String payeeBankCardId)
	{
		this.payeeBankCardId = payeeBankCardId;
	}

	@Column(name = "pay_pic_url", nullable = false, length = 128)
	public String getPayPicUrl()
	{
		return this.payPicUrl;
	}

	public void setPayPicUrl(String payPicUrl)
	{
		this.payPicUrl = payPicUrl;
	}

	@Column(name = "pay_remark", length = 256)
	public String getPayRemark()
	{
		return this.payRemark;
	}

	public void setPayRemark(String payRemark)
	{
		this.payRemark = payRemark;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus()
	{
		return this.status;
	}

	public void setStatus(byte status)
	{
		this.status = status;
	}

	@Column(name = "verify_date_long")
	public Long getVerifyDateLong()
	{
		return this.verifyDateLong;
	}

	public void setVerifyDateLong(Long verifyDateLong)
	{
		this.verifyDateLong = verifyDateLong;
	}

	@Column(name = "pay_date_long")
	public Long getPayDateLong()
	{
		return this.payDateLong;
	}

	public void setPayDateLong(Long payDateLong)
	{
		this.payDateLong = payDateLong;
	}

	@Column(name = "add_date_long", nullable = false)
	public long getAddDateLong()
	{
		return this.addDateLong;
	}

	public void setAddDateLong(long addDateLong)
	{
		this.addDateLong = addDateLong;
	}

	@Column(name = "update_date_long", nullable = false)
	public long getUpdateDateLong()
	{
		return this.updateDateLong;
	}

	public void setUpdateDateLong(long updateDateLong)
	{
		this.updateDateLong = updateDateLong;
	}
}
