package com.bet.orms;
// Generated 2018-4-22 12:03:18 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * WithdrawInfo generated by hbm2java
 */
@Entity
@Table(name = "withdraw_info", uniqueConstraints = @UniqueConstraint(columnNames = "withdraw_id"))
@Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
public class WithdrawInfo implements java.io.Serializable
{
	private static final long serialVersionUID = -2759715123425756787L;
	private Integer id;
	private String withdrawId;
	private String userId;
	private long money;
	private byte moneyUnit;
	private long userMoney;
	private long fee;
	private String payeeName;
	private String bankName;
	private String bankCardId;
	private String remark;
	private String payUserId;
	private String payPicUrl;
	private String payRemark;
	private byte status;
	private Long verifyDateLong;
	private Long payDateLong;
	private Long receiveDateLong;
	private long addDateLong;
	private long updateDateLong;

	public WithdrawInfo()
	{
	}

	public WithdrawInfo(String withdrawId, String userId, long money, byte moneyUnit, long userMoney, long fee, String payeeName, String bankName, String bankCardId, byte status, long addDateLong,
		long updateDateLong)
	{
		this.withdrawId = withdrawId;
		this.userId = userId;
		this.money = money;
		this.moneyUnit = moneyUnit;
		this.userMoney = userMoney;
		this.fee = fee;
		this.payeeName = payeeName;
		this.bankName = bankName;
		this.bankCardId = bankCardId;
		this.status = status;
		this.addDateLong = addDateLong;
		this.updateDateLong = updateDateLong;
	}

	public WithdrawInfo(String withdrawId, String userId, long money, byte moneyUnit, long userMoney, long fee, String payeeName, String bankName, String bankCardId, String remark, String payUserId,
		String payPicUrl, String payRemark, byte status, Long verifyDateLong, Long payDateLong, Long receiveDateLong, long addDateLong, long updateDateLong)
	{
		this.withdrawId = withdrawId;
		this.userId = userId;
		this.money = money;
		this.moneyUnit = moneyUnit;
		this.userMoney = userMoney;
		this.fee = fee;
		this.payeeName = payeeName;
		this.bankName = bankName;
		this.bankCardId = bankCardId;
		this.remark = remark;
		this.payUserId = payUserId;
		this.payPicUrl = payPicUrl;
		this.payRemark = payRemark;
		this.status = status;
		this.verifyDateLong = verifyDateLong;
		this.payDateLong = payDateLong;
		this.receiveDateLong = receiveDateLong;
		this.addDateLong = addDateLong;
		this.updateDateLong = updateDateLong;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "withdraw_id", unique = true, nullable = false, length = 16)
	public String getWithdrawId()
	{
		return this.withdrawId;
	}

	public void setWithdrawId(String withdrawId)
	{
		this.withdrawId = withdrawId;
	}

	@Column(name = "user_id", nullable = false, length = 16)
	public String getUserId()
	{
		return this.userId;
	}

	public void setUserId(String userId)
	{
		this.userId = userId;
	}

	@Column(name = "money", nullable = false)
	public long getMoney()
	{
		return this.money;
	}

	public void setMoney(long money)
	{
		this.money = money;
	}

	@Column(name = "money_unit", nullable = false)
	public byte getMoneyUnit()
	{
		return this.moneyUnit;
	}

	public void setMoneyUnit(byte moneyUnit)
	{
		this.moneyUnit = moneyUnit;
	}

	@Column(name = "user_money", nullable = false)
	public long getUserMoney()
	{
		return this.userMoney;
	}

	public void setUserMoney(long userMoney)
	{
		this.userMoney = userMoney;
	}

	@Column(name = "fee", nullable = false)
	public long getFee()
	{
		return this.fee;
	}

	public void setFee(long fee)
	{
		this.fee = fee;
	}

	@Column(name = "payee_name", nullable = false, length = 32)
	public String getPayeeName()
	{
		return this.payeeName;
	}

	public void setPayeeName(String payeeName)
	{
		this.payeeName = payeeName;
	}

	@Column(name = "bank_name", nullable = false, length = 32)
	public String getBankName()
	{
		return this.bankName;
	}

	public void setBankName(String bankName)
	{
		this.bankName = bankName;
	}

	@Column(name = "bank_card_id", nullable = false, length = 20)
	public String getBankCardId()
	{
		return this.bankCardId;
	}

	public void setBankCardId(String bankCardId)
	{
		this.bankCardId = bankCardId;
	}

	@Column(name = "remark", length = 256)
	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	@Column(name = "pay_user_id", length = 16)
	public String getPayUserId()
	{
		return this.payUserId;
	}

	public void setPayUserId(String payUserId)
	{
		this.payUserId = payUserId;
	}

	@Column(name = "pay_pic_url", length = 128)
	public String getPayPicUrl()
	{
		return this.payPicUrl;
	}

	public void setPayPicUrl(String payPicUrl)
	{
		this.payPicUrl = payPicUrl;
	}

	@Column(name = "pay_remark", length = 256)
	public String getPayRemark()
	{
		return this.payRemark;
	}

	public void setPayRemark(String payRemark)
	{
		this.payRemark = payRemark;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus()
	{
		return this.status;
	}

	public void setStatus(byte status)
	{
		this.status = status;
	}

	@Column(name = "verify_date_long")
	public Long getVerifyDateLong()
	{
		return this.verifyDateLong;
	}

	public void setVerifyDateLong(Long verifyDateLong)
	{
		this.verifyDateLong = verifyDateLong;
	}

	@Column(name = "pay_date_long")
	public Long getPayDateLong()
	{
		return this.payDateLong;
	}

	public void setPayDateLong(Long payDateLong)
	{
		this.payDateLong = payDateLong;
	}

	@Column(name = "receive_date_long")
	public Long getReceiveDateLong()
	{
		return this.receiveDateLong;
	}

	public void setReceiveDateLong(Long receiveDateLong)
	{
		this.receiveDateLong = receiveDateLong;
	}

	@Column(name = "add_date_long", nullable = false)
	public long getAddDateLong()
	{
		return this.addDateLong;
	}

	public void setAddDateLong(long addDateLong)
	{
		this.addDateLong = addDateLong;
	}

	@Column(name = "update_date_long", nullable = false)
	public long getUpdateDateLong()
	{
		return this.updateDateLong;
	}

	public void setUpdateDateLong(long updateDateLong)
	{
		this.updateDateLong = updateDateLong;
	}
}
